// Curated word list for passphrase generation.
// Based on common, easy-to-type English words (4-8 letters).
// ~1300 words provide ~10.3 bits of entropy per word.

export const WORDLIST: readonly string[] = [
  "acid", "acme", "acre", "aged", "aide", "aims", "arch", "area", "army",
  "atom", "aunt", "auto", "avid", "axis", "baby", "back", "badge", "bags",
  "bait", "bake", "bald", "ball", "band", "bank", "bare", "bark", "barn",
  "base", "bath", "bats", "beam", "bean", "bear", "beat", "beds", "beef",
  "been", "beer", "bell", "belt", "bend", "best", "bike", "bind", "bird",
  "bite", "bits", "blank", "blast", "blaze", "blend", "bless", "blind",
  "bliss", "block", "blood", "bloom", "blown", "blue", "bluff", "blunt",
  "board", "boat", "bold", "bolt", "bomb", "bond", "bone", "book", "boom",
  "boot", "born", "boss", "both", "bout", "bowl", "brave", "bread", "break",
  "breed", "brick", "bride", "brief", "bring", "broad", "brook", "brown",
  "brush", "buck", "bugs", "bulk", "bull", "bump", "burn", "burst", "cabin",
  "cable", "cage", "cake", "calm", "came", "camp", "cape", "caps", "card",
  "care", "cargo", "cart", "case", "cash", "cast", "cave", "cell", "chain",
  "chair", "chalk", "champ", "chart", "chase", "cheap", "check", "chess",
  "chief", "child", "chill", "chip", "choir", "chunk", "city", "civil",
  "claim", "clamp", "clap", "clash", "class", "clean", "clear", "clerk",
  "click", "cliff", "climb", "cling", "clip", "clock", "clone", "close",
  "cloth", "cloud", "club", "clue", "coach", "coast", "coat", "code",
  "coil", "cold", "colt", "comb", "come", "comic", "cone", "cook", "cool",
  "cope", "copy", "cord", "core", "corn", "cost", "couch", "count", "court",
  "cover", "crack", "craft", "crane", "crash", "crawl", "crazy", "cream",
  "creek", "crew", "crisp", "cross", "crowd", "crown", "crush", "cubic",
  "cups", "cure", "curl", "curve", "cycle", "daily", "dairy", "dance",
  "dare", "dark", "dart", "dash", "data", "dawn", "days", "dead", "deaf",
  "deal", "dear", "debt", "decay", "deck", "deed", "deep", "deer", "delta",
  "dense", "depth", "derby", "desk", "dew", "dial", "dice", "diet", "dirt",
  "disc", "dish", "dock", "dodge", "dogs", "dome", "done", "donor", "doom",
  "door", "dose", "dots", "doubt", "dough", "dove", "down", "draft",
  "drain", "drake", "drama", "drank", "drape", "draw", "dream", "dress",
  "drift", "drill", "drink", "drive", "drop", "drove", "drums", "drunk",
  "dryer", "duck", "dues", "duke", "dull", "dump", "dune", "dusk", "dust",
  "duty", "dwarf", "dying", "each", "eager", "eagle", "earn", "earth",
  "ease", "east", "easy", "edge", "eight", "elder", "elect", "elite",
  "else", "empty", "enemy", "entry", "equal", "error", "essay", "event",
  "every", "exact", "exam", "exile", "exist", "extra", "fable", "face",
  "fact", "faint", "fair", "faith", "fall", "false", "fame", "fancy",
  "farm", "fast", "fate", "fault", "feast", "feat", "fence", "ferry",
  "fetch", "fever", "fiber", "field", "fifth", "fifty", "fight", "file",
  "film", "final", "find", "fine", "fire", "firm", "first", "fish", "five",
  "fixed", "flag", "flame", "flash", "flat", "fleet", "flesh", "flick",
  "flies", "fling", "flip", "float", "flock", "flood", "floor", "flour",
  "flow", "fluid", "flush", "foam", "focus", "fold", "folk", "fond",
  "font", "food", "fool", "foot", "force", "frond", "form", "forth",
  "forum", "found", "four", "frame", "frank", "fraud", "free", "fresh",
  "front", "frost", "fruit", "fuel", "full", "fund", "funny", "fury",
  "fuse", "fuzzy", "gain", "gala", "game", "gang", "gap", "gate", "gauge",
  "gave", "gear", "gene", "genre", "ghost", "giant", "gift", "given",
  "glad", "gland", "glass", "gleam", "glide", "globe", "gloom", "glory",
  "gloss", "glove", "glow", "glue", "goat", "goes", "gold", "golf",
  "gone", "good", "goose", "gripe", "grace", "grade", "grain", "grand",
  "grant", "grape", "graph", "grasp", "grass", "grave", "great", "green",
  "greet", "grief", "grill", "grin", "grind", "grip", "grit", "gross",
  "group", "grove", "grown", "guard", "guess", "guest", "guide", "guild",
  "guilt", "guise", "gulf", "guru", "gust", "guts", "habit", "half",
  "hall", "halt", "hands", "handy", "hang", "happy", "hard", "harm",
  "haste", "hatch", "hate", "haunt", "haven", "hawk", "haze", "head",
  "heal", "heap", "heart", "heat", "hedge", "heels", "hefty", "held",
  "hello", "help", "hence", "herb", "herd", "hero", "hike", "hill",
  "hint", "hire", "hobby", "hold", "hole", "home", "honey", "honor",
  "hood", "hook", "hope", "horn", "horse", "host", "hotel", "hour",
  "house", "hover", "huge", "hull", "human", "humor", "hunt", "hurry",
  "hurt", "hymn", "icon", "idea", "image", "inch", "index", "indie",
  "inner", "input", "irony", "ivory", "jacket", "jade", "jail", "jazz",
  "jewel", "jobs", "join", "joke", "jolly", "judge", "juice", "jumbo",
  "jump", "jungle", "jury", "keep", "kept", "kick", "kids", "kind", "king",
  "kiss", "kite", "knack", "kneel", "knelt", "knife", "knit", "knock",
  "knot", "known", "label", "labor", "lace", "lack", "lake", "lamp",
  "lance", "land", "lane", "large", "laser", "last", "latch", "later",
  "laugh", "lawn", "layer", "lead", "leaf", "leak", "lean", "learn",
  "lease", "least", "left", "legal", "lemon", "lens", "level", "lever",
  "light", "liked", "limb", "lime", "limit", "line", "linen", "link",
  "lions", "list", "liter", "live", "liver", "lobby", "local", "lock",
  "lodge", "logic", "lone", "long", "look", "lord", "loss", "lost",
  "loud", "love", "lover", "lower", "loyal", "luck", "lunar", "lunch",
  "lung", "lure", "magic", "major", "maker", "mango", "manor", "maple",
  "march", "marks", "marsh", "masks", "match", "mayor", "maze", "meals",
  "media", "melon", "mercy", "merge", "merit", "mesh", "metal", "meter",
  "midst", "might", "mild", "milk", "mill", "mimic", "mind", "mine",
  "minor", "minus", "mirth", "mist", "mixer", "moat", "model", "moist",
  "mold", "money", "month", "mood", "moon", "moral", "motor", "mound",
  "mount", "mouse", "mouth", "moved", "movie", "much", "mural", "music",
  "must", "myths", "naive", "naked", "name", "naval", "near", "neat",
  "nerve", "nest", "never", "newly", "next", "night", "nine", "noble",
  "nod", "noise", "none", "norm", "north", "noted", "novel", "nurse",
  "nylon", "oasis", "occur", "ocean", "olive", "once", "onset", "opera",
  "orbit", "order", "omega", "other", "ought", "outer", "oven", "owned",
  "owner", "oxide", "pace", "pack", "pact", "page", "paid", "pain",
  "paint", "pair", "palm", "panel", "panic", "paper", "park", "party",
  "paste", "patch", "path", "patio", "pause", "peace", "peach", "pearl",
  "pedal", "penny", "perch", "phase", "phone", "photo", "piano", "picks",
  "piece", "pilot", "pinch", "pine", "pitch", "pixel", "pizza", "place",
  "plain", "plane", "plank", "plant", "plate", "plaza", "plead", "pleas",
  "plier", "pluck", "plumb", "plume", "plump", "plunge", "plus", "pocket",
  "poem", "poet", "point", "polar", "polls", "pond", "pools", "porch",
  "ports", "posed", "post", "pouch", "pound", "pour", "power", "pray",
  "press", "price", "pride", "prime", "print", "prior", "prize", "probe",
  "proof", "prose", "proud", "prove", "prune", "pubic", "pudge", "pulse",
  "pump", "punch", "pupil", "pure", "purse", "quest", "queue", "quick",
  "quiet", "quilt", "quirk", "quota", "quote", "race", "radar", "radio",
  "rage", "raid", "rails", "rain", "raise", "rally", "ranch", "range",
  "rapid", "rare", "raven", "reach", "react", "reads", "ready", "realm",
  "rebel", "refer", "reign", "relax", "relay", "relic", "renew", "reply",
  "reset", "resin", "rest", "retry", "rider", "ridge", "rifle", "rigid",
  "rings", "rinse", "risen", "risky", "rival", "river", "roads", "roast",
  "robot", "rocks", "rocky", "rode", "roles", "roman", "roof", "rooms",
  "roots", "rope", "rough", "round", "route", "rover", "royal", "rugby",
  "ruins", "ruled", "ruler", "rumor", "rural", "rusty", "sadly", "saint",
  "sake", "salad", "salon", "salts", "sandy", "sauce", "saved", "scale",
  "scare", "scene", "scent", "scope", "score", "scout", "scrap", "seed",
  "seize", "sense", "serve", "setup", "seven", "shade", "shaft", "shake",
  "shall", "shame", "shape", "share", "shark", "sharp", "shave", "shed",
  "sheer", "sheet", "shelf", "shell", "shift", "shine", "shirt", "shock",
  "shoes", "shoot", "shore", "short", "shout", "shown", "shrub", "siege",
  "sight", "sigma", "signs", "silk", "silly", "since", "sixth", "sixty",
  "sized", "skate", "skill", "skull", "slate", "sleep", "slice", "slide",
  "slim", "slope", "slots", "small", "smart", "smell", "smile", "smoke",
  "snake", "snare", "sneak", "solar", "solid", "solve", "songs", "sonic",
  "sorry", "souls", "sound", "south", "space", "spare", "spark", "speak",
  "speed", "spell", "spend", "spent", "spice", "spike", "spine", "split",
  "spoke", "spoon", "sport", "spray", "squad", "stack", "staff", "stage",
  "stain", "stake", "stale", "stall", "stamp", "stand", "stark", "start",
  "state", "stays", "steam", "steel", "steep", "steer", "stems", "steps",
  "stern", "stick", "stiff", "still", "stock", "stole", "stone", "stood",
  "stool", "store", "storm", "story", "stout", "stove", "strap", "straw",
  "strip", "stuck", "stuff", "stump", "style", "sugar", "suite", "sunny",
  "super", "surge", "swamp", "swarm", "swear", "sweep", "sweet", "swept",
  "swift", "swing", "sworn", "sword", "syrup", "table", "taken", "tales",
  "talks", "tanks", "tapes", "taste", "taxes", "teach", "teams", "tears",
  "tempo", "tend", "tense", "tenth", "terms", "tests", "their", "theme",
  "thick", "thing", "think", "third", "those", "three", "threw", "throw",
  "thumb", "tidal", "tides", "tiger", "tight", "tiles", "timer", "tired",
  "title", "toast", "today", "token", "tonal", "tones", "tools", "tooth",
  "topic", "torch", "total", "touch", "tough", "tours", "tower", "towns",
  "trace", "track", "trade", "trail", "train", "trait", "traps", "trash",
  "treat", "trees", "trend", "trial", "tribe", "trick", "tried", "troop",
  "truck", "truly", "trump", "trunk", "trust", "truth", "tubes", "tulip",
  "tumor", "tunes", "turns", "tutor", "twice", "twist", "ultra", "uncle",
  "under", "unify", "union", "unite", "unity", "until", "upper", "upset",
  "urban", "urged", "usage", "usual", "valid", "valor", "valve", "vault",
  "venue", "verse", "video", "vigor", "vinyl", "viola", "virus", "visit",
  "vital", "vivid", "vocal", "voice", "voter", "wagon", "waist", "walks",
  "walls", "wards", "warns", "waste", "watch", "water", "waves", "wealth",
  "wheat", "wheel", "where", "while", "white", "whole", "wider", "widow",
  "width", "winds", "wings", "wired", "witch", "woman", "woods", "words",
  "works", "world", "worms", "worry", "worse", "worst", "worth", "wound",
  "wrath", "wrist", "wrote", "yacht", "yards", "years", "yield", "young",
  "yours", "youth", "zeros", "zones",
] as const;
