import { defineConfig } from "vitest/config";
import path from "path";

export default defineConfig({
  test: {
    globals: true,
    environment: "node",
    include: [
      "src/**/*.test.{ts,tsx}",
      "e2e/helpers/*.test.ts",
      "scripts/__tests__/**/*.test.mjs",
    ],
    exclude: ["src/**/*.integration.test.ts"],
    setupFiles: ["src/__tests__/setup.ts"],
    coverage: {
      provider: "v8",
      include: [
        "src/app/api/**/*.ts",
        "src/lib/crypto/crypto-utils.ts",
        "src/lib/crypto/crypto-client.ts",
        "src/lib/crypto/crypto-aad.ts",
        "src/lib/crypto/crypto-emergency.ts",
        "src/lib/crypto/crypto-recovery.ts",
        "src/lib/auth/access/team-auth.ts",
        "src/lib/crypto/crypto-server.ts",
        "src/lib/crypto/crypto-team.ts",
        "src/lib/team/team-vault-core.tsx",
        "src/lib/password-generator.ts",
        "src/lib/email/**/*.ts",
        "src/lib/auth/session/auth-adapter.ts",
        "src/lib/auth/tokens/scim-token.ts",
        "src/lib/scim/*.ts",
        "src/lib/auth/webauthn/webauthn-authorize.ts",
        "src/lib/auth/webauthn/webauthn-server.ts",
        "src/lib/auth/session/check-auth.ts",
        "src/lib/http/parse-body.ts",
        "src/lib/http/with-request-log.ts",
        "src/lib/auth/session/auth-or-token.ts",
        "src/lib/auth/policy/access-restriction.ts",
        "src/lib/auth/policy/account-lockout.ts",
        "src/lib/webhook-dispatcher.ts",
        "src/lib/audit/audit.ts",
        "src/lib/audit/audit-outbox.ts",
        "src/lib/audit/audit-query.ts",
        "src/proxy.ts",
        "src/components/**/*.{ts,tsx}",
        "src/app/global-error.tsx",
        "src/lib/key-provider/**/*.ts",
        "src/lib/prisma/prisma-error.ts",
        "src/lib/security/sentry-sanitize.ts",
        "src/lib/mcp/**/*.ts",
        "src/lib/security/password-policy-validation.ts",
        "src/lib/auth/tokens/extension-token.ts",
        "src/lib/inject-extension-bridge-code.ts",
      ],
      exclude: [
        "src/app/api/auth/\\[...nextauth\\]/**",
        "src/components/**/*.test.{ts,tsx}",
      ],
      thresholds: {
        lines: 60,
        "src/lib/auth/session/auth-or-token.ts": { lines: 80 },
        "src/lib/crypto/crypto-server.ts": { lines: 80 },
        "src/lib/crypto/crypto-team.ts": { lines: 80 },
      },
    },
    isolate: true,
    testTimeout: 10000,
  },
  resolve: {
    alias: {
      "@": path.resolve(__dirname, "src"),
    },
  },
});
