import type { AuditAction, AuditScope } from "@prisma/client";

export const AUDIT_SCOPE = {
  PERSONAL: "PERSONAL",
  ORG: "ORG",
} as const satisfies Record<AuditScope, AuditScope>;

export const AUDIT_ACTION = {
  AUTH_LOGIN: "AUTH_LOGIN",
  AUTH_LOGOUT: "AUTH_LOGOUT",
  ENTRY_BULK_DELETE: "ENTRY_BULK_DELETE",
  ENTRY_BULK_ARCHIVE: "ENTRY_BULK_ARCHIVE",
  ENTRY_BULK_UNARCHIVE: "ENTRY_BULK_UNARCHIVE",
  ENTRY_IMPORT: "ENTRY_IMPORT",
  ENTRY_CREATE: "ENTRY_CREATE",
  ENTRY_UPDATE: "ENTRY_UPDATE",
  ENTRY_DELETE: "ENTRY_DELETE",
  ENTRY_RESTORE: "ENTRY_RESTORE",
  ENTRY_EXPORT: "ENTRY_EXPORT",
  ATTACHMENT_UPLOAD: "ATTACHMENT_UPLOAD",
  ATTACHMENT_DELETE: "ATTACHMENT_DELETE",
  ORG_MEMBER_INVITE: "ORG_MEMBER_INVITE",
  ORG_MEMBER_REMOVE: "ORG_MEMBER_REMOVE",
  ORG_ROLE_UPDATE: "ORG_ROLE_UPDATE",
  SHARE_CREATE: "SHARE_CREATE",
  SHARE_REVOKE: "SHARE_REVOKE",
  EMERGENCY_GRANT_CREATE: "EMERGENCY_GRANT_CREATE",
  EMERGENCY_GRANT_ACCEPT: "EMERGENCY_GRANT_ACCEPT",
  EMERGENCY_GRANT_REJECT: "EMERGENCY_GRANT_REJECT",
  EMERGENCY_GRANT_CONFIRM: "EMERGENCY_GRANT_CONFIRM",
  EMERGENCY_ACCESS_REQUEST: "EMERGENCY_ACCESS_REQUEST",
  EMERGENCY_ACCESS_ACTIVATE: "EMERGENCY_ACCESS_ACTIVATE",
  EMERGENCY_ACCESS_REVOKE: "EMERGENCY_ACCESS_REVOKE",
  EMERGENCY_VAULT_ACCESS: "EMERGENCY_VAULT_ACCESS",
} as const satisfies Record<AuditAction, AuditAction>;

export type AuditScopeValue =
  (typeof AUDIT_SCOPE)[keyof typeof AUDIT_SCOPE];

export type AuditActionValue =
  (typeof AUDIT_ACTION)[keyof typeof AUDIT_ACTION];

export const AUDIT_ACTION_VALUES = [
  AUDIT_ACTION.AUTH_LOGIN,
  AUDIT_ACTION.AUTH_LOGOUT,
  AUDIT_ACTION.ENTRY_BULK_DELETE,
  AUDIT_ACTION.ENTRY_BULK_ARCHIVE,
  AUDIT_ACTION.ENTRY_BULK_UNARCHIVE,
  AUDIT_ACTION.ENTRY_IMPORT,
  AUDIT_ACTION.ENTRY_CREATE,
  AUDIT_ACTION.ENTRY_UPDATE,
  AUDIT_ACTION.ENTRY_DELETE,
  AUDIT_ACTION.ENTRY_RESTORE,
  AUDIT_ACTION.ENTRY_EXPORT,
  AUDIT_ACTION.ATTACHMENT_UPLOAD,
  AUDIT_ACTION.ATTACHMENT_DELETE,
  AUDIT_ACTION.ORG_MEMBER_INVITE,
  AUDIT_ACTION.ORG_MEMBER_REMOVE,
  AUDIT_ACTION.ORG_ROLE_UPDATE,
  AUDIT_ACTION.SHARE_CREATE,
  AUDIT_ACTION.SHARE_REVOKE,
  AUDIT_ACTION.EMERGENCY_GRANT_CREATE,
  AUDIT_ACTION.EMERGENCY_GRANT_ACCEPT,
  AUDIT_ACTION.EMERGENCY_GRANT_REJECT,
  AUDIT_ACTION.EMERGENCY_GRANT_CONFIRM,
  AUDIT_ACTION.EMERGENCY_ACCESS_REQUEST,
  AUDIT_ACTION.EMERGENCY_ACCESS_ACTIVATE,
  AUDIT_ACTION.EMERGENCY_ACCESS_REVOKE,
  AUDIT_ACTION.EMERGENCY_VAULT_ACCESS,
] as const;

export const AUDIT_ACTION_GROUP = {
  AUTH: "group:auth",
  ENTRY: "group:entry",
  TRANSFER: "group:transfer",
  ATTACHMENT: "group:attachment",
  ORG: "group:org",
  SHARE: "group:share",
  EMERGENCY: "group:emergency",
} as const;

export const AUDIT_ACTION_GROUPS_PERSONAL: Record<string, AuditAction[]> = {
  [AUDIT_ACTION_GROUP.AUTH]: [
    AUDIT_ACTION.AUTH_LOGIN,
    AUDIT_ACTION.AUTH_LOGOUT,
  ],
  [AUDIT_ACTION_GROUP.ENTRY]: [
    AUDIT_ACTION.ENTRY_BULK_DELETE,
    AUDIT_ACTION.ENTRY_BULK_ARCHIVE,
    AUDIT_ACTION.ENTRY_BULK_UNARCHIVE,
    AUDIT_ACTION.ENTRY_CREATE,
    AUDIT_ACTION.ENTRY_UPDATE,
    AUDIT_ACTION.ENTRY_DELETE,
    AUDIT_ACTION.ENTRY_RESTORE,
  ],
  [AUDIT_ACTION_GROUP.TRANSFER]: [
    AUDIT_ACTION.ENTRY_IMPORT,
    AUDIT_ACTION.ENTRY_EXPORT,
  ],
  [AUDIT_ACTION_GROUP.ATTACHMENT]: [
    AUDIT_ACTION.ATTACHMENT_UPLOAD,
    AUDIT_ACTION.ATTACHMENT_DELETE,
  ],
  [AUDIT_ACTION_GROUP.ORG]: [
    AUDIT_ACTION.ORG_MEMBER_INVITE,
    AUDIT_ACTION.ORG_MEMBER_REMOVE,
    AUDIT_ACTION.ORG_ROLE_UPDATE,
  ],
  [AUDIT_ACTION_GROUP.SHARE]: [
    AUDIT_ACTION.SHARE_CREATE,
    AUDIT_ACTION.SHARE_REVOKE,
  ],
  [AUDIT_ACTION_GROUP.EMERGENCY]: [
    AUDIT_ACTION.EMERGENCY_GRANT_CREATE,
    AUDIT_ACTION.EMERGENCY_GRANT_ACCEPT,
    AUDIT_ACTION.EMERGENCY_GRANT_REJECT,
    AUDIT_ACTION.EMERGENCY_GRANT_CONFIRM,
    AUDIT_ACTION.EMERGENCY_ACCESS_REQUEST,
    AUDIT_ACTION.EMERGENCY_ACCESS_ACTIVATE,
    AUDIT_ACTION.EMERGENCY_ACCESS_REVOKE,
    AUDIT_ACTION.EMERGENCY_VAULT_ACCESS,
  ],
};

export const AUDIT_ACTION_GROUPS_ORG: Record<string, AuditAction[]> = {
  [AUDIT_ACTION_GROUP.ENTRY]: [
    AUDIT_ACTION.ENTRY_CREATE,
    AUDIT_ACTION.ENTRY_UPDATE,
    AUDIT_ACTION.ENTRY_DELETE,
    AUDIT_ACTION.ENTRY_RESTORE,
  ],
  [AUDIT_ACTION_GROUP.TRANSFER]: [AUDIT_ACTION.ENTRY_EXPORT],
  [AUDIT_ACTION_GROUP.ATTACHMENT]: [
    AUDIT_ACTION.ATTACHMENT_UPLOAD,
    AUDIT_ACTION.ATTACHMENT_DELETE,
  ],
  [AUDIT_ACTION_GROUP.ORG]: [
    AUDIT_ACTION.ORG_MEMBER_INVITE,
    AUDIT_ACTION.ORG_MEMBER_REMOVE,
    AUDIT_ACTION.ORG_ROLE_UPDATE,
  ],
  [AUDIT_ACTION_GROUP.SHARE]: [
    AUDIT_ACTION.SHARE_CREATE,
    AUDIT_ACTION.SHARE_REVOKE,
  ],
};

export const AUDIT_ACTION_EMERGENCY_PREFIX = "EMERGENCY_";
