-- Remove legacy ENTRY_BULK_DELETE action and map existing rows to ENTRY_BULK_TRASH
ALTER TYPE "AuditAction" RENAME TO "AuditAction_old";

CREATE TYPE "AuditAction" AS ENUM (
  'AUTH_LOGIN',
  'AUTH_LOGOUT',
  'ENTRY_BULK_ARCHIVE',
  'ENTRY_BULK_UNARCHIVE',
  'ENTRY_BULK_RESTORE',
  'ENTRY_BULK_TRASH',
  'ENTRY_EMPTY_TRASH',
  'ENTRY_IMPORT',
  'ENTRY_CREATE',
  'ENTRY_UPDATE',
  'ENTRY_DELETE',
  'ENTRY_TRASH',
  'ENTRY_PERMANENT_DELETE',
  'ENTRY_RESTORE',
  'ENTRY_EXPORT',
  'ATTACHMENT_UPLOAD',
  'ATTACHMENT_DELETE',
  'ORG_MEMBER_INVITE',
  'ORG_MEMBER_REMOVE',
  'ORG_ROLE_UPDATE',
  'SHARE_CREATE',
  'SHARE_REVOKE',
  'EMERGENCY_GRANT_CREATE',
  'EMERGENCY_GRANT_ACCEPT',
  'EMERGENCY_GRANT_REJECT',
  'EMERGENCY_GRANT_CONFIRM',
  'EMERGENCY_ACCESS_REQUEST',
  'EMERGENCY_ACCESS_ACTIVATE',
  'EMERGENCY_ACCESS_REVOKE',
  'EMERGENCY_VAULT_ACCESS'
);

ALTER TABLE "audit_logs"
ALTER COLUMN "action" TYPE "AuditAction"
USING (
  CASE
    WHEN "action"::text = 'ENTRY_BULK_DELETE' THEN 'ENTRY_BULK_TRASH'::"AuditAction"
    ELSE "action"::text::"AuditAction"
  END
);

DROP TYPE "AuditAction_old";
