-- AlterEnum: add delivery target CRUD audit actions
ALTER TYPE "AuditAction" ADD VALUE 'AUDIT_DELIVERY_TARGET_CREATE';
ALTER TYPE "AuditAction" ADD VALUE 'AUDIT_DELIVERY_TARGET_DEACTIVATE';
ALTER TYPE "AuditAction" ADD VALUE 'AUDIT_DELIVERY_TARGET_REACTIVATE';
