import { vi } from "vitest";
import type { TeamPasswordFormLifecycleSetters } from "@/hooks/use-team-password-form-state";

export function createTeamPasswordFormLifecycleSettersMock(): TeamPasswordFormLifecycleSetters {
  const noop = vi.fn();
  return {
    setTitle: noop,
    setUsername: noop,
    setPassword: noop,
    setContent: noop,
    setUrl: noop,
    setNotes: noop,
    setSelectedTags: noop,
    setGeneratorSettings: noop,
    setCustomFields: noop,
    setTotp: noop,
    setShowTotpInput: noop,
    setCardholderName: noop,
    setCardNumber: noop,
    setBrand: noop,
    setBrandSource: noop,
    setExpiryMonth: noop,
    setExpiryYear: noop,
    setCvv: noop,
    setFullName: noop,
    setAddress: noop,
    setPhone: noop,
    setEmail: noop,
    setDateOfBirth: noop,
    setNationality: noop,
    setIdNumber: noop,
    setIssueDate: noop,
    setExpiryDate: noop,
    setRelyingPartyId: noop,
    setRelyingPartyName: noop,
    setCredentialId: noop,
    setCreationDate: noop,
    setDeviceInfo: noop,
    setBankName: noop,
    setAccountType: noop,
    setAccountHolderName: noop,
    setAccountNumber: noop,
    setShowAccountNumber: noop,
    setRoutingNumber: noop,
    setShowRoutingNumber: noop,
    setSwiftBic: noop,
    setIban: noop,
    setBranchName: noop,
    setSoftwareName: noop,
    setLicenseKey: noop,
    setShowLicenseKey: noop,
    setVersion: noop,
    setLicensee: noop,
    setPurchaseDate: noop,
    setExpirationDate: noop,
    setTeamFolderId: noop,
    setRequireReprompt: noop,
    setExpiresAt: noop,
    setShowPassword: noop,
    setShowGenerator: noop,
    setShowCardNumber: noop,
    setShowCvv: noop,
    setShowIdNumber: noop,
    setShowCredentialId: noop,
    setAttachments: noop,
    setSaving: noop,
    setDobError: noop,
    setExpiryError: noop,
  };
}
