"use client";

import type {
  TeamPasswordFormValues,
  TeamPasswordFormSettersState,
} from "@/hooks/use-team-password-form-state";
import {
  buildTeamEntrySpecificCallbacks,
} from "@/hooks/team-entry-specific-fields-callbacks";
import {
  buildTeamEntrySpecificTextProps,
} from "@/hooks/team-entry-specific-fields-text-props";
import type {
  TeamEntrySpecificFieldsBuilderArgs,
  TeamEntrySpecificFieldsProps,
} from "@/hooks/team-entry-specific-fields-types";

export function buildTeamEntrySpecificFieldsProps({
  entryKind,
  entryCopy,
  translations,
  notes,
  onNotesChange,
  title,
  onTitleChange,
  username,
  onUsernameChange,
  password,
  onPasswordChange,
  showPassword,
  onToggleShowPassword,
  generatorSummary,
  showGenerator,
  onToggleGenerator,
  generatorSettings,
  onGeneratorUse,
  url,
  onUrlChange,
  content,
  onContentChange,
  cardholderName,
  onCardholderNameChange,
  brand,
  onBrandChange,
  cardNumber,
  onCardNumberChange,
  showCardNumber,
  onToggleCardNumber,
  maxInputLength,
  showLengthError,
  showLuhnError,
  detectedBrand,
  hasBrandHint,
  lengthHint,
  expiryMonth,
  onExpiryMonthChange,
  expiryYear,
  onExpiryYearChange,
  cvv,
  onCvvChange,
  showCvv,
  onToggleCvv,
  fullName,
  onFullNameChange,
  address,
  onAddressChange,
  phone,
  onPhoneChange,
  email,
  onEmailChange,
  dateOfBirth,
  onDateOfBirthChange,
  nationality,
  onNationalityChange,
  idNumber,
  onIdNumberChange,
  showIdNumber,
  onToggleIdNumber,
  issueDate,
  onIssueDateChange,
  expiryDate,
  onExpiryDateChange,
  dobError,
  expiryError,
  relyingPartyId,
  onRelyingPartyIdChange,
  relyingPartyName,
  onRelyingPartyNameChange,
  credentialId,
  onCredentialIdChange,
  showCredentialId,
  onToggleCredentialId,
  creationDate,
  onCreationDateChange,
  deviceInfo,
  onDeviceInfoChange,
  bankName,
  onBankNameChange,
  accountType,
  onAccountTypeChange,
  accountHolderName,
  onAccountHolderNameChange,
  accountNumber,
  onAccountNumberChange,
  showAccountNumber,
  onToggleAccountNumber,
  routingNumber,
  onRoutingNumberChange,
  showRoutingNumber,
  onToggleRoutingNumber,
  swiftBic,
  onSwiftBicChange,
  iban,
  onIbanChange,
  branchName,
  onBranchNameChange,
  softwareName,
  onSoftwareNameChange,
  licenseKey,
  onLicenseKeyChange,
  showLicenseKey,
  onToggleLicenseKey,
  version,
  onVersionChange,
  licensee,
  onLicenseeChange,
  purchaseDate,
  onPurchaseDateChange,
  expirationDate,
  onExpirationDateChange,
  softwareLicenseExpiryError,
}: TeamEntrySpecificFieldsBuilderArgs): TeamEntrySpecificFieldsProps {
  const computedTextProps = buildTeamEntrySpecificTextProps(translations, entryCopy, lengthHint);

  return {
    entryKind,
    ...computedTextProps,
    notes,
    onNotesChange,
    content,
    onContentChange,
    title,
    onTitleChange,
    username,
    onUsernameChange,
    password,
    onPasswordChange,
    showPassword,
    onToggleShowPassword,
    generatorSummary,
    showGenerator,
    onToggleGenerator,
    generatorSettings,
    onGeneratorUse,
    url,
    onUrlChange,
    cardholderName,
    onCardholderNameChange,
    brand,
    onBrandChange,
    cardNumber,
    onCardNumberChange,
    showCardNumber,
    onToggleCardNumber,
    maxInputLength,
    showLengthError,
    showLuhnError,
    detectedBrand,
    hasBrandHint,
    expiryMonth,
    onExpiryMonthChange,
    expiryYear,
    onExpiryYearChange,
    cvv,
    onCvvChange,
    showCvv,
    onToggleCvv,
    fullName,
    onFullNameChange,
    address,
    onAddressChange,
    phone,
    onPhoneChange,
    email,
    onEmailChange,
    dateOfBirth,
    onDateOfBirthChange,
    nationality,
    onNationalityChange,
    idNumber,
    onIdNumberChange,
    showIdNumber,
    onToggleIdNumber,
    issueDate,
    onIssueDateChange,
    expiryDate,
    onExpiryDateChange,
    dobError,
    expiryError,
    relyingPartyId,
    onRelyingPartyIdChange,
    relyingPartyName,
    onRelyingPartyNameChange,
    credentialId,
    onCredentialIdChange,
    showCredentialId,
    onToggleCredentialId,
    creationDate,
    onCreationDateChange,
    deviceInfo,
    onDeviceInfoChange,
    bankName,
    onBankNameChange,
    accountType,
    onAccountTypeChange,
    accountHolderName,
    onAccountHolderNameChange,
    accountNumber,
    onAccountNumberChange,
    showAccountNumber,
    onToggleAccountNumber,
    routingNumber,
    onRoutingNumberChange,
    showRoutingNumber,
    onToggleRoutingNumber,
    swiftBic,
    onSwiftBicChange,
    iban,
    onIbanChange,
    branchName,
    onBranchNameChange,
    softwareName,
    onSoftwareNameChange,
    licenseKey,
    onLicenseKeyChange,
    showLicenseKey,
    onToggleLicenseKey,
    version,
    onVersionChange,
    licensee,
    onLicenseeChange,
    purchaseDate,
    onPurchaseDateChange,
    expirationDate,
    onExpirationDateChange,
    softwareLicenseExpiryError,
  };
}

export type BuildTeamEntrySpecificFieldsPropsFromStateArgs = Pick<
  TeamEntrySpecificFieldsBuilderArgs,
  | "entryKind"
  | "entryCopy"
  | "translations"
  | "generatorSummary"
  | "maxInputLength"
  | "showLengthError"
  | "showLuhnError"
  | "detectedBrand"
  | "hasBrandHint"
  | "lengthHint"
  | "onCardNumberChange"
> & {
  values: TeamPasswordFormValues;
  setters: TeamPasswordFormSettersState;
};

type TeamEntrySpecificCallbacks = ReturnType<typeof buildTeamEntrySpecificCallbacks>;

export function buildTeamEntrySpecificFieldsBuilderArgsFromState({
  entryKind,
  entryCopy,
  translations,
  values,
  callbacks,
  generatorSummary,
  onCardNumberChange,
  maxInputLength,
  showLengthError,
  showLuhnError,
  detectedBrand,
  hasBrandHint,
  lengthHint,
}: Omit<BuildTeamEntrySpecificFieldsPropsFromStateArgs, "setters"> & {
  callbacks: TeamEntrySpecificCallbacks;
}): TeamEntrySpecificFieldsBuilderArgs {
  return {
    entryKind,
    entryCopy,
    translations,
    notes: values.notes,
    onNotesChange: callbacks.onNotesChange,
    title: values.title,
    onTitleChange: callbacks.onTitleChange,
    username: values.username,
    onUsernameChange: callbacks.onUsernameChange,
    password: values.password,
    onPasswordChange: callbacks.onPasswordChange,
    showPassword: values.showPassword,
    onToggleShowPassword: callbacks.onToggleShowPassword,
    generatorSummary,
    showGenerator: values.showGenerator,
    onToggleGenerator: callbacks.onToggleGenerator,
    generatorSettings: values.generatorSettings,
    onGeneratorUse: callbacks.onGeneratorUse,
    url: values.url,
    onUrlChange: callbacks.onUrlChange,
    content: values.content,
    onContentChange: callbacks.onContentChange,
    cardholderName: values.cardholderName,
    onCardholderNameChange: callbacks.onCardholderNameChange,
    brand: values.brand,
    onBrandChange: callbacks.onBrandChange,
    cardNumber: values.cardNumber,
    onCardNumberChange,
    showCardNumber: values.showCardNumber,
    onToggleCardNumber: callbacks.onToggleCardNumber,
    maxInputLength,
    showLengthError,
    showLuhnError,
    detectedBrand,
    hasBrandHint,
    lengthHint,
    expiryMonth: values.expiryMonth,
    onExpiryMonthChange: callbacks.onExpiryMonthChange,
    expiryYear: values.expiryYear,
    onExpiryYearChange: callbacks.onExpiryYearChange,
    cvv: values.cvv,
    onCvvChange: callbacks.onCvvChange,
    showCvv: values.showCvv,
    onToggleCvv: callbacks.onToggleCvv,
    fullName: values.fullName,
    onFullNameChange: callbacks.onFullNameChange,
    address: values.address,
    onAddressChange: callbacks.onAddressChange,
    phone: values.phone,
    onPhoneChange: callbacks.onPhoneChange,
    email: values.email,
    onEmailChange: callbacks.onEmailChange,
    dateOfBirth: values.dateOfBirth,
    onDateOfBirthChange: callbacks.onDateOfBirthChange,
    nationality: values.nationality,
    onNationalityChange: callbacks.onNationalityChange,
    idNumber: values.idNumber,
    onIdNumberChange: callbacks.onIdNumberChange,
    showIdNumber: values.showIdNumber,
    onToggleIdNumber: callbacks.onToggleIdNumber,
    issueDate: values.issueDate,
    onIssueDateChange: callbacks.onIssueDateChange,
    expiryDate: values.expiryDate,
    onExpiryDateChange: callbacks.onExpiryDateChange,
    dobError: values.dobError,
    expiryError: values.expiryError,
    relyingPartyId: values.relyingPartyId,
    onRelyingPartyIdChange: callbacks.onRelyingPartyIdChange,
    relyingPartyName: values.relyingPartyName,
    onRelyingPartyNameChange: callbacks.onRelyingPartyNameChange,
    credentialId: values.credentialId,
    onCredentialIdChange: callbacks.onCredentialIdChange,
    showCredentialId: values.showCredentialId,
    onToggleCredentialId: callbacks.onToggleCredentialId,
    creationDate: values.creationDate,
    onCreationDateChange: callbacks.onCreationDateChange,
    deviceInfo: values.deviceInfo,
    onDeviceInfoChange: callbacks.onDeviceInfoChange,
    bankName: values.bankName,
    onBankNameChange: callbacks.onBankNameChange,
    accountType: values.accountType,
    onAccountTypeChange: callbacks.onAccountTypeChange,
    accountHolderName: values.accountHolderName,
    onAccountHolderNameChange: callbacks.onAccountHolderNameChange,
    accountNumber: values.accountNumber,
    onAccountNumberChange: callbacks.onAccountNumberChange,
    showAccountNumber: values.showAccountNumber,
    onToggleAccountNumber: callbacks.onToggleAccountNumber,
    routingNumber: values.routingNumber,
    onRoutingNumberChange: callbacks.onRoutingNumberChange,
    showRoutingNumber: values.showRoutingNumber,
    onToggleRoutingNumber: callbacks.onToggleRoutingNumber,
    swiftBic: values.swiftBic,
    onSwiftBicChange: callbacks.onSwiftBicChange,
    iban: values.iban,
    onIbanChange: callbacks.onIbanChange,
    branchName: values.branchName,
    onBranchNameChange: callbacks.onBranchNameChange,
    softwareName: values.softwareName,
    onSoftwareNameChange: callbacks.onSoftwareNameChange,
    licenseKey: values.licenseKey,
    onLicenseKeyChange: callbacks.onLicenseKeyChange,
    showLicenseKey: values.showLicenseKey,
    onToggleLicenseKey: callbacks.onToggleLicenseKey,
    version: values.version,
    onVersionChange: callbacks.onVersionChange,
    licensee: values.licensee,
    onLicenseeChange: callbacks.onLicenseeChange,
    purchaseDate: values.purchaseDate,
    onPurchaseDateChange: callbacks.onPurchaseDateChange,
    expirationDate: values.expirationDate,
    onExpirationDateChange: callbacks.onExpirationDateChange,
    softwareLicenseExpiryError: values.expiryError,
  };
}

export function buildTeamEntrySpecificFieldsPropsFromState({
  entryKind,
  entryCopy,
  translations,
  values,
  setters,
  generatorSummary,
  onCardNumberChange,
  maxInputLength,
  showLengthError,
  showLuhnError,
  detectedBrand,
  hasBrandHint,
  lengthHint,
}: BuildTeamEntrySpecificFieldsPropsFromStateArgs): TeamEntrySpecificFieldsProps {
  const callbacks = buildTeamEntrySpecificCallbacks(values, setters);
  const builderArgs = buildTeamEntrySpecificFieldsBuilderArgsFromState({
    entryKind,
    entryCopy,
    translations,
    values,
    callbacks,
    generatorSummary,
    onCardNumberChange,
    maxInputLength,
    showLengthError,
    showLuhnError,
    detectedBrand,
    hasBrandHint,
    lengthHint,
  });

  return buildTeamEntrySpecificFieldsProps(builderArgs);
}
