import type { AuditAction, AuditScope, ActorType } from "@prisma/client";

export const ACTOR_TYPE = {
  HUMAN: "HUMAN",
  SERVICE_ACCOUNT: "SERVICE_ACCOUNT",
  MCP_AGENT: "MCP_AGENT",
  SYSTEM: "SYSTEM",
  ANONYMOUS: "ANONYMOUS",
} as const satisfies Record<ActorType, ActorType>;

export const AUDIT_SCOPE = {
  PERSONAL: "PERSONAL",
  TEAM: "TEAM",
  TENANT: "TENANT",
} as const satisfies Record<AuditScope, AuditScope>;

export const AUDIT_ACTION = {
  AUTH_LOGIN: "AUTH_LOGIN",
  AUTH_LOGOUT: "AUTH_LOGOUT",
  ENTRY_BULK_TRASH: "ENTRY_BULK_TRASH",
  ENTRY_EMPTY_TRASH: "ENTRY_EMPTY_TRASH",
  ENTRY_BULK_ARCHIVE: "ENTRY_BULK_ARCHIVE",
  ENTRY_BULK_UNARCHIVE: "ENTRY_BULK_UNARCHIVE",
  ENTRY_BULK_RESTORE: "ENTRY_BULK_RESTORE",
  ENTRY_BULK_IMPORT: "ENTRY_BULK_IMPORT",
  ENTRY_IMPORT: "ENTRY_IMPORT",
  ENTRY_CREATE: "ENTRY_CREATE",
  ENTRY_UPDATE: "ENTRY_UPDATE",
  ENTRY_DELETE: "ENTRY_DELETE",
  ENTRY_TRASH: "ENTRY_TRASH",
  ENTRY_PERMANENT_DELETE: "ENTRY_PERMANENT_DELETE",
  ENTRY_RESTORE: "ENTRY_RESTORE",
  ENTRY_EXPORT: "ENTRY_EXPORT",
  ATTACHMENT_UPLOAD: "ATTACHMENT_UPLOAD",
  ATTACHMENT_DELETE: "ATTACHMENT_DELETE",
  TEAM_MEMBER_ADD: "TEAM_MEMBER_ADD",
  TEAM_MEMBER_INVITE: "TEAM_MEMBER_INVITE",
  TEAM_MEMBER_REMOVE: "TEAM_MEMBER_REMOVE",
  TEAM_ROLE_UPDATE: "TEAM_ROLE_UPDATE",
  SHARE_CREATE: "SHARE_CREATE",
  SHARE_REVOKE: "SHARE_REVOKE",
  SEND_CREATE: "SEND_CREATE",
  SEND_REVOKE: "SEND_REVOKE",
  SHARE_ACCESS_VERIFY_SUCCESS: "SHARE_ACCESS_VERIFY_SUCCESS",
  SHARE_ACCESS_VERIFY_FAILED: "SHARE_ACCESS_VERIFY_FAILED",
  EMERGENCY_GRANT_CREATE: "EMERGENCY_GRANT_CREATE",
  EMERGENCY_GRANT_ACCEPT: "EMERGENCY_GRANT_ACCEPT",
  EMERGENCY_GRANT_REJECT: "EMERGENCY_GRANT_REJECT",
  EMERGENCY_GRANT_CONFIRM: "EMERGENCY_GRANT_CONFIRM",
  EMERGENCY_ACCESS_REQUEST: "EMERGENCY_ACCESS_REQUEST",
  EMERGENCY_ACCESS_ACTIVATE: "EMERGENCY_ACCESS_ACTIVATE",
  EMERGENCY_ACCESS_REVOKE: "EMERGENCY_ACCESS_REVOKE",
  EMERGENCY_VAULT_ACCESS: "EMERGENCY_VAULT_ACCESS",
  VAULT_UNLOCK_FAILED: "VAULT_UNLOCK_FAILED",
  VAULT_LOCKOUT_TRIGGERED: "VAULT_LOCKOUT_TRIGGERED",
  RECOVERY_KEY_CREATED: "RECOVERY_KEY_CREATED",
  RECOVERY_KEY_REGENERATED: "RECOVERY_KEY_REGENERATED",
  RECOVERY_PASSPHRASE_RESET: "RECOVERY_PASSPHRASE_RESET",
  VAULT_SETUP: "VAULT_SETUP",
  VAULT_RESET_EXECUTED: "VAULT_RESET_EXECUTED",
  FOLDER_CREATE: "FOLDER_CREATE",
  FOLDER_UPDATE: "FOLDER_UPDATE",
  FOLDER_DELETE: "FOLDER_DELETE",
  ENTRY_HISTORY_RESTORE: "ENTRY_HISTORY_RESTORE",
  HISTORY_PURGE: "HISTORY_PURGE",
  // SIEM orientation: rows logged before this constant was introduced used
  // HISTORY_PURGE for both entry-history retention purges AND audit-log
  // retention purges. Forward queries should distinguish:
  //   HISTORY_PURGE     → password-entry history retention purge
  //   AUDIT_LOG_PURGE   → audit_logs table retention purge
  // Pre-merge purge-audit-logs rows can also be disambiguated by
  // metadata.targetTable === "auditLog" when present.
  AUDIT_LOG_PURGE: "AUDIT_LOG_PURGE",
  MASTER_KEY_ROTATION: "MASTER_KEY_ROTATION",
  VERIFIER_PEPPER_ROTATE_BEGIN: "VERIFIER_PEPPER_ROTATE_BEGIN",
  VERIFIER_PEPPER_ROTATE_COMPLETE: "VERIFIER_PEPPER_ROTATE_COMPLETE",
  VERIFIER_PEPPER_ROTATE_ROLLBACK: "VERIFIER_PEPPER_ROTATE_ROLLBACK",
  VERIFIER_PEPPER_MISSING: "VERIFIER_PEPPER_MISSING",
  VAULT_KEY_ROTATION: "VAULT_KEY_ROTATION",
  SESSION_REVOKE: "SESSION_REVOKE",
  SESSION_REVOKE_ALL: "SESSION_REVOKE_ALL",
  TEAM_E2E_MIGRATION: "TEAM_E2E_MIGRATION",
  TEAM_KEY_ROTATION: "TEAM_KEY_ROTATION",
  TEAM_MEMBER_KEY_DISTRIBUTE: "TEAM_MEMBER_KEY_DISTRIBUTE",
  SCIM_TOKEN_CREATE: "SCIM_TOKEN_CREATE",
  SCIM_TOKEN_REVOKE: "SCIM_TOKEN_REVOKE",
  SCIM_USER_CREATE: "SCIM_USER_CREATE",
  SCIM_USER_UPDATE: "SCIM_USER_UPDATE",
  SCIM_USER_DEACTIVATE: "SCIM_USER_DEACTIVATE",
  SCIM_USER_REACTIVATE: "SCIM_USER_REACTIVATE",
  SCIM_USER_DELETE: "SCIM_USER_DELETE",
  SCIM_GROUP_UPDATE: "SCIM_GROUP_UPDATE",
  POLICY_UPDATE: "POLICY_UPDATE",
  TEAM_POLICY_CLAMPED_BY_TENANT: "TEAM_POLICY_CLAMPED_BY_TENANT",
  EXTENSION_TOKEN_FAMILY_REVOKED: "EXTENSION_TOKEN_FAMILY_REVOKED",
  AUDIT_LOG_DOWNLOAD: "AUDIT_LOG_DOWNLOAD",
  WEBHOOK_CREATE: "WEBHOOK_CREATE",
  WEBHOOK_DELETE: "WEBHOOK_DELETE",
  WEBHOOK_DELIVERY_FAILED: "WEBHOOK_DELIVERY_FAILED",
  WATCHTOWER_ALERT_SENT: "WATCHTOWER_ALERT_SENT",
  ADMIN_VAULT_RESET_INITIATE: "ADMIN_VAULT_RESET_INITIATE",
  ADMIN_VAULT_RESET_APPROVE: "ADMIN_VAULT_RESET_APPROVE",
  ADMIN_VAULT_RESET_EXECUTE: "ADMIN_VAULT_RESET_EXECUTE",
  ADMIN_VAULT_RESET_REVOKE: "ADMIN_VAULT_RESET_REVOKE",
  API_KEY_CREATE: "API_KEY_CREATE",
  API_KEY_REVOKE: "API_KEY_REVOKE",
  TRAVEL_MODE_ENABLE: "TRAVEL_MODE_ENABLE",
  TRAVEL_MODE_DISABLE: "TRAVEL_MODE_DISABLE",
  TRAVEL_MODE_DISABLE_FAILED: "TRAVEL_MODE_DISABLE_FAILED",
  WEBAUTHN_CREDENTIAL_REGISTER: "WEBAUTHN_CREDENTIAL_REGISTER",
  WEBAUTHN_CREDENTIAL_DELETE: "WEBAUTHN_CREDENTIAL_DELETE",
  DIRECTORY_SYNC_CONFIG_CREATE: "DIRECTORY_SYNC_CONFIG_CREATE",
  DIRECTORY_SYNC_CONFIG_UPDATE: "DIRECTORY_SYNC_CONFIG_UPDATE",
  DIRECTORY_SYNC_CONFIG_DELETE: "DIRECTORY_SYNC_CONFIG_DELETE",
  DIRECTORY_SYNC_RUN: "DIRECTORY_SYNC_RUN",
  DIRECTORY_SYNC_STALE_RESET: "DIRECTORY_SYNC_STALE_RESET",
  SESSION_EVICTED: "SESSION_EVICTED",
  ENTRY_HISTORY_REENCRYPT: "ENTRY_HISTORY_REENCRYPT",
  ACCESS_DENIED: "ACCESS_DENIED",
  TENANT_ROLE_UPDATE: "TENANT_ROLE_UPDATE",
  PERSONAL_LOG_ACCESS_REQUEST: "PERSONAL_LOG_ACCESS_REQUEST",
  PERSONAL_LOG_ACCESS_VIEW: "PERSONAL_LOG_ACCESS_VIEW",
  PERSONAL_LOG_ACCESS_REVOKE: "PERSONAL_LOG_ACCESS_REVOKE",
  PERSONAL_LOG_ACCESS_EXPIRE: "PERSONAL_LOG_ACCESS_EXPIRE",
  TENANT_WEBHOOK_CREATE: "TENANT_WEBHOOK_CREATE",
  TENANT_WEBHOOK_DELETE: "TENANT_WEBHOOK_DELETE",
  TENANT_WEBHOOK_DELIVERY_FAILED: "TENANT_WEBHOOK_DELIVERY_FAILED",
  SERVICE_ACCOUNT_CREATE: "SERVICE_ACCOUNT_CREATE",
  SERVICE_ACCOUNT_UPDATE: "SERVICE_ACCOUNT_UPDATE",
  SERVICE_ACCOUNT_DELETE: "SERVICE_ACCOUNT_DELETE",
  SERVICE_ACCOUNT_TOKEN_CREATE: "SERVICE_ACCOUNT_TOKEN_CREATE",
  SERVICE_ACCOUNT_TOKEN_REVOKE: "SERVICE_ACCOUNT_TOKEN_REVOKE",
  ACCESS_REQUEST_CREATE: "ACCESS_REQUEST_CREATE",
  ACCESS_REQUEST_APPROVE: "ACCESS_REQUEST_APPROVE",
  ACCESS_REQUEST_DENY: "ACCESS_REQUEST_DENY",
  MCP_CLIENT_CREATE: "MCP_CLIENT_CREATE",
  MCP_CLIENT_UPDATE: "MCP_CLIENT_UPDATE",
  MCP_CLIENT_DELETE: "MCP_CLIENT_DELETE",
  MCP_CLIENT_DCR_REGISTER: "MCP_CLIENT_DCR_REGISTER",
  MCP_CLIENT_DCR_CLAIM: "MCP_CLIENT_DCR_CLAIM",
  MCP_CLIENT_DCR_CLEANUP: "MCP_CLIENT_DCR_CLEANUP",
  MCP_CLIENT_DCR_CLEANUP_DEPRECATED_CALL: "MCP_CLIENT_DCR_CLEANUP_DEPRECATED_CALL",
  MCP_CONSENT_GRANT: "MCP_CONSENT_GRANT",
  MCP_CONSENT_DENY: "MCP_CONSENT_DENY",
  MCP_REFRESH_TOKEN_ROTATE: "MCP_REFRESH_TOKEN_ROTATE",
  MCP_REFRESH_TOKEN_REPLAY: "MCP_REFRESH_TOKEN_REPLAY",
  DELEGATION_CREATE: "DELEGATION_CREATE",
  DELEGATION_REVOKE: "DELEGATION_REVOKE",
  DELEGATION_EXPIRE: "DELEGATION_EXPIRE",
  DELEGATION_READ: "DELEGATION_READ",
  DELEGATION_CHECK: "DELEGATION_CHECK",
  MCP_CONNECTION_REVOKE: "MCP_CONNECTION_REVOKE",
  MCP_CONNECTION_REVOKE_ALL: "MCP_CONNECTION_REVOKE_ALL",
  PASSKEY_ENFORCEMENT_BLOCKED: "PASSKEY_ENFORCEMENT_BLOCKED",
  EXTENSION_BRIDGE_CODE_ISSUE: "EXTENSION_BRIDGE_CODE_ISSUE",
  EXTENSION_TOKEN_EXCHANGE_SUCCESS: "EXTENSION_TOKEN_EXCHANGE_SUCCESS",
  EXTENSION_TOKEN_EXCHANGE_FAILURE: "EXTENSION_TOKEN_EXCHANGE_FAILURE",
  AUDIT_OUTBOX_REAPED: "AUDIT_OUTBOX_REAPED",
  AUDIT_OUTBOX_DEAD_LETTER: "AUDIT_OUTBOX_DEAD_LETTER",
  AUDIT_OUTBOX_RETENTION_PURGED: "AUDIT_OUTBOX_RETENTION_PURGED",
  AUDIT_OUTBOX_METRICS_VIEW: "AUDIT_OUTBOX_METRICS_VIEW",
  AUDIT_OUTBOX_PURGE_EXECUTED: "AUDIT_OUTBOX_PURGE_EXECUTED",
  AUDIT_DELIVERY_FAILED: "AUDIT_DELIVERY_FAILED",
  AUDIT_DELIVERY_DEAD_LETTER: "AUDIT_DELIVERY_DEAD_LETTER",
  AUDIT_CHAIN_VERIFY: "AUDIT_CHAIN_VERIFY",
  AUDIT_DELIVERY_TARGET_CREATE: "AUDIT_DELIVERY_TARGET_CREATE",
  AUDIT_DELIVERY_TARGET_DEACTIVATE: "AUDIT_DELIVERY_TARGET_DEACTIVATE",
  AUDIT_DELIVERY_TARGET_REACTIVATE: "AUDIT_DELIVERY_TARGET_REACTIVATE",
  OPERATOR_TOKEN_CREATE: "OPERATOR_TOKEN_CREATE",
  OPERATOR_TOKEN_REVOKE: "OPERATOR_TOKEN_REVOKE",
} as const satisfies Record<AuditAction, AuditAction>;

export type AuditScopeValue =
  (typeof AUDIT_SCOPE)[keyof typeof AUDIT_SCOPE];

export type AuditActionValue =
  (typeof AUDIT_ACTION)[keyof typeof AUDIT_ACTION];

export const AUDIT_ACTION_VALUES = [
  AUDIT_ACTION.AUTH_LOGIN,
  AUDIT_ACTION.AUTH_LOGOUT,
  AUDIT_ACTION.ENTRY_BULK_TRASH,
  AUDIT_ACTION.ENTRY_EMPTY_TRASH,
  AUDIT_ACTION.ENTRY_BULK_ARCHIVE,
  AUDIT_ACTION.ENTRY_BULK_UNARCHIVE,
  AUDIT_ACTION.ENTRY_BULK_RESTORE,
  AUDIT_ACTION.ENTRY_BULK_IMPORT,
  AUDIT_ACTION.ENTRY_IMPORT,
  AUDIT_ACTION.ENTRY_CREATE,
  AUDIT_ACTION.ENTRY_UPDATE,
  AUDIT_ACTION.ENTRY_DELETE,
  AUDIT_ACTION.ENTRY_TRASH,
  AUDIT_ACTION.ENTRY_PERMANENT_DELETE,
  AUDIT_ACTION.ENTRY_RESTORE,
  AUDIT_ACTION.ENTRY_EXPORT,
  AUDIT_ACTION.ATTACHMENT_UPLOAD,
  AUDIT_ACTION.ATTACHMENT_DELETE,
  AUDIT_ACTION.TEAM_MEMBER_ADD,
  AUDIT_ACTION.TEAM_MEMBER_INVITE,
  AUDIT_ACTION.TEAM_MEMBER_REMOVE,
  AUDIT_ACTION.TEAM_ROLE_UPDATE,
  AUDIT_ACTION.SHARE_CREATE,
  AUDIT_ACTION.SHARE_REVOKE,
  AUDIT_ACTION.EMERGENCY_GRANT_CREATE,
  AUDIT_ACTION.EMERGENCY_GRANT_ACCEPT,
  AUDIT_ACTION.EMERGENCY_GRANT_REJECT,
  AUDIT_ACTION.EMERGENCY_GRANT_CONFIRM,
  AUDIT_ACTION.EMERGENCY_ACCESS_REQUEST,
  AUDIT_ACTION.EMERGENCY_ACCESS_ACTIVATE,
  AUDIT_ACTION.EMERGENCY_ACCESS_REVOKE,
  AUDIT_ACTION.EMERGENCY_VAULT_ACCESS,
  AUDIT_ACTION.VAULT_UNLOCK_FAILED,
  AUDIT_ACTION.VAULT_LOCKOUT_TRIGGERED,
  AUDIT_ACTION.RECOVERY_KEY_CREATED,
  AUDIT_ACTION.RECOVERY_KEY_REGENERATED,
  AUDIT_ACTION.RECOVERY_PASSPHRASE_RESET,
  AUDIT_ACTION.VAULT_SETUP,
  AUDIT_ACTION.VAULT_RESET_EXECUTED,
  AUDIT_ACTION.FOLDER_CREATE,
  AUDIT_ACTION.FOLDER_UPDATE,
  AUDIT_ACTION.FOLDER_DELETE,
  AUDIT_ACTION.ENTRY_HISTORY_RESTORE,
  AUDIT_ACTION.HISTORY_PURGE,
  AUDIT_ACTION.AUDIT_LOG_PURGE,
  AUDIT_ACTION.SEND_CREATE,
  AUDIT_ACTION.SEND_REVOKE,
  AUDIT_ACTION.SHARE_ACCESS_VERIFY_SUCCESS,
  AUDIT_ACTION.SHARE_ACCESS_VERIFY_FAILED,
  AUDIT_ACTION.MASTER_KEY_ROTATION,
  AUDIT_ACTION.VERIFIER_PEPPER_ROTATE_BEGIN,
  AUDIT_ACTION.VERIFIER_PEPPER_ROTATE_COMPLETE,
  AUDIT_ACTION.VERIFIER_PEPPER_ROTATE_ROLLBACK,
  AUDIT_ACTION.VERIFIER_PEPPER_MISSING,
  AUDIT_ACTION.VAULT_KEY_ROTATION,
  AUDIT_ACTION.SESSION_REVOKE,
  AUDIT_ACTION.SESSION_REVOKE_ALL,
  AUDIT_ACTION.TEAM_E2E_MIGRATION,
  AUDIT_ACTION.TEAM_KEY_ROTATION,
  AUDIT_ACTION.TEAM_MEMBER_KEY_DISTRIBUTE,
  AUDIT_ACTION.SCIM_TOKEN_CREATE,
  AUDIT_ACTION.SCIM_TOKEN_REVOKE,
  AUDIT_ACTION.SCIM_USER_CREATE,
  AUDIT_ACTION.SCIM_USER_UPDATE,
  AUDIT_ACTION.SCIM_USER_DEACTIVATE,
  AUDIT_ACTION.SCIM_USER_REACTIVATE,
  AUDIT_ACTION.SCIM_USER_DELETE,
  AUDIT_ACTION.SCIM_GROUP_UPDATE,
  AUDIT_ACTION.POLICY_UPDATE,
  AUDIT_ACTION.TEAM_POLICY_CLAMPED_BY_TENANT,
  AUDIT_ACTION.EXTENSION_TOKEN_FAMILY_REVOKED,
  AUDIT_ACTION.AUDIT_LOG_DOWNLOAD,
  AUDIT_ACTION.WEBHOOK_CREATE,
  AUDIT_ACTION.WEBHOOK_DELETE,
  AUDIT_ACTION.WEBHOOK_DELIVERY_FAILED,
  AUDIT_ACTION.WATCHTOWER_ALERT_SENT,
  AUDIT_ACTION.ADMIN_VAULT_RESET_INITIATE,
  AUDIT_ACTION.ADMIN_VAULT_RESET_APPROVE,
  AUDIT_ACTION.ADMIN_VAULT_RESET_EXECUTE,
  AUDIT_ACTION.ADMIN_VAULT_RESET_REVOKE,
  AUDIT_ACTION.API_KEY_CREATE,
  AUDIT_ACTION.API_KEY_REVOKE,
  AUDIT_ACTION.TRAVEL_MODE_ENABLE,
  AUDIT_ACTION.TRAVEL_MODE_DISABLE,
  AUDIT_ACTION.TRAVEL_MODE_DISABLE_FAILED,
  AUDIT_ACTION.WEBAUTHN_CREDENTIAL_REGISTER,
  AUDIT_ACTION.WEBAUTHN_CREDENTIAL_DELETE,
  AUDIT_ACTION.DIRECTORY_SYNC_CONFIG_CREATE,
  AUDIT_ACTION.DIRECTORY_SYNC_CONFIG_UPDATE,
  AUDIT_ACTION.DIRECTORY_SYNC_CONFIG_DELETE,
  AUDIT_ACTION.DIRECTORY_SYNC_RUN,
  AUDIT_ACTION.DIRECTORY_SYNC_STALE_RESET,
  AUDIT_ACTION.SESSION_EVICTED,
  AUDIT_ACTION.ENTRY_HISTORY_REENCRYPT,
  AUDIT_ACTION.ACCESS_DENIED,
  AUDIT_ACTION.TENANT_ROLE_UPDATE,
  AUDIT_ACTION.PERSONAL_LOG_ACCESS_REQUEST,
  AUDIT_ACTION.PERSONAL_LOG_ACCESS_VIEW,
  AUDIT_ACTION.PERSONAL_LOG_ACCESS_REVOKE,
  AUDIT_ACTION.PERSONAL_LOG_ACCESS_EXPIRE,
  AUDIT_ACTION.TENANT_WEBHOOK_CREATE,
  AUDIT_ACTION.TENANT_WEBHOOK_DELETE,
  AUDIT_ACTION.TENANT_WEBHOOK_DELIVERY_FAILED,
  AUDIT_ACTION.SERVICE_ACCOUNT_CREATE,
  AUDIT_ACTION.SERVICE_ACCOUNT_UPDATE,
  AUDIT_ACTION.SERVICE_ACCOUNT_DELETE,
  AUDIT_ACTION.SERVICE_ACCOUNT_TOKEN_CREATE,
  AUDIT_ACTION.SERVICE_ACCOUNT_TOKEN_REVOKE,
  AUDIT_ACTION.ACCESS_REQUEST_CREATE,
  AUDIT_ACTION.ACCESS_REQUEST_APPROVE,
  AUDIT_ACTION.ACCESS_REQUEST_DENY,
  AUDIT_ACTION.MCP_CLIENT_CREATE,
  AUDIT_ACTION.MCP_CLIENT_UPDATE,
  AUDIT_ACTION.MCP_CLIENT_DELETE,
  AUDIT_ACTION.MCP_CLIENT_DCR_REGISTER,
  AUDIT_ACTION.MCP_CLIENT_DCR_CLAIM,
  AUDIT_ACTION.MCP_CLIENT_DCR_CLEANUP,
  AUDIT_ACTION.MCP_CLIENT_DCR_CLEANUP_DEPRECATED_CALL,
  AUDIT_ACTION.MCP_CONSENT_GRANT,
  AUDIT_ACTION.MCP_CONSENT_DENY,
  AUDIT_ACTION.MCP_REFRESH_TOKEN_ROTATE,
  AUDIT_ACTION.MCP_REFRESH_TOKEN_REPLAY,
  AUDIT_ACTION.DELEGATION_CREATE,
  AUDIT_ACTION.DELEGATION_REVOKE,
  AUDIT_ACTION.DELEGATION_EXPIRE,
  AUDIT_ACTION.DELEGATION_READ,
  AUDIT_ACTION.DELEGATION_CHECK,
  AUDIT_ACTION.MCP_CONNECTION_REVOKE,
  AUDIT_ACTION.MCP_CONNECTION_REVOKE_ALL,
  AUDIT_ACTION.PASSKEY_ENFORCEMENT_BLOCKED,
  AUDIT_ACTION.EXTENSION_BRIDGE_CODE_ISSUE,
  AUDIT_ACTION.EXTENSION_TOKEN_EXCHANGE_SUCCESS,
  AUDIT_ACTION.EXTENSION_TOKEN_EXCHANGE_FAILURE,
  AUDIT_ACTION.AUDIT_OUTBOX_REAPED,
  AUDIT_ACTION.AUDIT_OUTBOX_DEAD_LETTER,
  AUDIT_ACTION.AUDIT_OUTBOX_RETENTION_PURGED,
  AUDIT_ACTION.AUDIT_OUTBOX_METRICS_VIEW,
  AUDIT_ACTION.AUDIT_OUTBOX_PURGE_EXECUTED,
  AUDIT_ACTION.AUDIT_DELIVERY_FAILED,
  AUDIT_ACTION.AUDIT_DELIVERY_DEAD_LETTER,
  AUDIT_ACTION.AUDIT_CHAIN_VERIFY,
  AUDIT_ACTION.AUDIT_DELIVERY_TARGET_CREATE,
  AUDIT_ACTION.AUDIT_DELIVERY_TARGET_DEACTIVATE,
  AUDIT_ACTION.AUDIT_DELIVERY_TARGET_REACTIVATE,
  AUDIT_ACTION.OPERATOR_TOKEN_CREATE,
  AUDIT_ACTION.OPERATOR_TOKEN_REVOKE,
] as const;

export const AUDIT_ACTION_GROUP = {
  AUTH: "group:auth",
  ENTRY: "group:entry",
  BULK: "group:bulk",
  TRANSFER: "group:transfer",
  ATTACHMENT: "group:attachment",
  FOLDER: "group:folder",
  HISTORY: "group:history",
  TEAM: "group:team",
  SHARE: "group:share",
  SEND: "group:send",
  EMERGENCY: "group:emergency",
  ADMIN: "group:admin",
  SCIM: "group:scim",
  WEBHOOK: "group:webhook",
  API_KEYS: "group:apiKeys",
  TRAVEL_MODE: "group:travelMode",
  WEBAUTHN: "group:webauthn",
  DIRECTORY_SYNC: "group:directorySync",
  BREAKGLASS: "group:breakglass",
  TENANT_WEBHOOK: "group:tenantWebhook",
  SERVICE_ACCOUNT: "group:serviceAccount",
  MCP_CLIENT: "group:mcpClient",
  DELEGATION: "group:delegation",
  MAINTENANCE: "group:maintenance",
  AUDIT_DELIVERY_TARGET: "group:auditDeliveryTarget",
} as const;

export const AUDIT_ACTION_GROUPS_PERSONAL: Record<string, AuditAction[]> = {
  [AUDIT_ACTION_GROUP.AUTH]: [
    AUDIT_ACTION.AUTH_LOGIN,
    AUDIT_ACTION.AUTH_LOGOUT,
    AUDIT_ACTION.VAULT_UNLOCK_FAILED,
    AUDIT_ACTION.VAULT_LOCKOUT_TRIGGERED,
    AUDIT_ACTION.RECOVERY_KEY_CREATED,
    AUDIT_ACTION.RECOVERY_KEY_REGENERATED,
    AUDIT_ACTION.RECOVERY_PASSPHRASE_RESET,
    AUDIT_ACTION.VAULT_SETUP,
    AUDIT_ACTION.VAULT_RESET_EXECUTED,
    AUDIT_ACTION.SESSION_REVOKE,
    AUDIT_ACTION.SESSION_REVOKE_ALL,
    AUDIT_ACTION.SESSION_EVICTED,
    AUDIT_ACTION.WATCHTOWER_ALERT_SENT,
    AUDIT_ACTION.ADMIN_VAULT_RESET_INITIATE,
    AUDIT_ACTION.ADMIN_VAULT_RESET_APPROVE,
    AUDIT_ACTION.ADMIN_VAULT_RESET_EXECUTE,
    AUDIT_ACTION.ADMIN_VAULT_RESET_REVOKE,
    AUDIT_ACTION.EXTENSION_BRIDGE_CODE_ISSUE,
    AUDIT_ACTION.EXTENSION_TOKEN_EXCHANGE_SUCCESS,
    AUDIT_ACTION.EXTENSION_TOKEN_EXCHANGE_FAILURE,
    AUDIT_ACTION.EXTENSION_TOKEN_FAMILY_REVOKED,
  ],
  [AUDIT_ACTION_GROUP.ENTRY]: [
    AUDIT_ACTION.ENTRY_CREATE,
    AUDIT_ACTION.ENTRY_UPDATE,
    AUDIT_ACTION.ENTRY_TRASH,
    AUDIT_ACTION.ENTRY_PERMANENT_DELETE,
    AUDIT_ACTION.ENTRY_RESTORE,
  ],
  [AUDIT_ACTION_GROUP.BULK]: [
    AUDIT_ACTION.ENTRY_BULK_TRASH,
    AUDIT_ACTION.ENTRY_EMPTY_TRASH,
    AUDIT_ACTION.ENTRY_BULK_ARCHIVE,
    AUDIT_ACTION.ENTRY_BULK_UNARCHIVE,
    AUDIT_ACTION.ENTRY_BULK_RESTORE,
  ],
  [AUDIT_ACTION_GROUP.TRANSFER]: [
    AUDIT_ACTION.ENTRY_BULK_IMPORT,
    AUDIT_ACTION.ENTRY_IMPORT,
    AUDIT_ACTION.ENTRY_EXPORT,
  ],
  [AUDIT_ACTION_GROUP.ATTACHMENT]: [
    AUDIT_ACTION.ATTACHMENT_UPLOAD,
    AUDIT_ACTION.ATTACHMENT_DELETE,
  ],
  [AUDIT_ACTION_GROUP.TEAM]: [
    AUDIT_ACTION.TEAM_MEMBER_INVITE,
    AUDIT_ACTION.TEAM_MEMBER_REMOVE,
    AUDIT_ACTION.TEAM_ROLE_UPDATE,
  ],
  [AUDIT_ACTION_GROUP.FOLDER]: [
    AUDIT_ACTION.FOLDER_CREATE,
    AUDIT_ACTION.FOLDER_UPDATE,
    AUDIT_ACTION.FOLDER_DELETE,
  ],
  [AUDIT_ACTION_GROUP.HISTORY]: [
    AUDIT_ACTION.ENTRY_HISTORY_RESTORE,
    AUDIT_ACTION.HISTORY_PURGE,
    AUDIT_ACTION.ENTRY_HISTORY_REENCRYPT,
  ],
  [AUDIT_ACTION_GROUP.SHARE]: [
    AUDIT_ACTION.SHARE_CREATE,
    AUDIT_ACTION.SHARE_REVOKE,
    AUDIT_ACTION.SHARE_ACCESS_VERIFY_SUCCESS,
    AUDIT_ACTION.SHARE_ACCESS_VERIFY_FAILED,
  ],
  [AUDIT_ACTION_GROUP.SEND]: [
    AUDIT_ACTION.SEND_CREATE,
    AUDIT_ACTION.SEND_REVOKE,
  ],
  [AUDIT_ACTION_GROUP.EMERGENCY]: [
    AUDIT_ACTION.EMERGENCY_GRANT_CREATE,
    AUDIT_ACTION.EMERGENCY_GRANT_ACCEPT,
    AUDIT_ACTION.EMERGENCY_GRANT_REJECT,
    AUDIT_ACTION.EMERGENCY_GRANT_CONFIRM,
    AUDIT_ACTION.EMERGENCY_ACCESS_REQUEST,
    AUDIT_ACTION.EMERGENCY_ACCESS_ACTIVATE,
    AUDIT_ACTION.EMERGENCY_ACCESS_REVOKE,
    AUDIT_ACTION.EMERGENCY_VAULT_ACCESS,
  ],
  [AUDIT_ACTION_GROUP.API_KEYS]: [
    AUDIT_ACTION.API_KEY_CREATE,
    AUDIT_ACTION.API_KEY_REVOKE,
  ],
  [AUDIT_ACTION_GROUP.TRAVEL_MODE]: [
    AUDIT_ACTION.TRAVEL_MODE_ENABLE,
    AUDIT_ACTION.TRAVEL_MODE_DISABLE,
    AUDIT_ACTION.TRAVEL_MODE_DISABLE_FAILED,
  ],
  [AUDIT_ACTION_GROUP.WEBAUTHN]: [
    AUDIT_ACTION.WEBAUTHN_CREDENTIAL_REGISTER,
    AUDIT_ACTION.WEBAUTHN_CREDENTIAL_DELETE,
  ],
  [AUDIT_ACTION_GROUP.DELEGATION]: [
    AUDIT_ACTION.DELEGATION_CREATE,
    AUDIT_ACTION.DELEGATION_REVOKE,
    AUDIT_ACTION.DELEGATION_EXPIRE,
    AUDIT_ACTION.DELEGATION_READ,
    AUDIT_ACTION.DELEGATION_CHECK,
    AUDIT_ACTION.MCP_CONNECTION_REVOKE,
    AUDIT_ACTION.MCP_CONNECTION_REVOKE_ALL,
  ],
};

export const AUDIT_ACTION_GROUPS_TEAM: Record<string, AuditAction[]> = {
  [AUDIT_ACTION_GROUP.ENTRY]: [
    AUDIT_ACTION.ENTRY_CREATE,
    AUDIT_ACTION.ENTRY_UPDATE,
    AUDIT_ACTION.ENTRY_DELETE,
    AUDIT_ACTION.ENTRY_TRASH,
    AUDIT_ACTION.ENTRY_PERMANENT_DELETE,
    AUDIT_ACTION.ENTRY_RESTORE,
  ],
  [AUDIT_ACTION_GROUP.BULK]: [
    AUDIT_ACTION.ENTRY_BULK_TRASH,
    AUDIT_ACTION.ENTRY_EMPTY_TRASH,
    AUDIT_ACTION.ENTRY_BULK_ARCHIVE,
    AUDIT_ACTION.ENTRY_BULK_UNARCHIVE,
    AUDIT_ACTION.ENTRY_BULK_RESTORE,
  ],
  [AUDIT_ACTION_GROUP.TRANSFER]: [AUDIT_ACTION.ENTRY_BULK_IMPORT, AUDIT_ACTION.ENTRY_EXPORT],
  [AUDIT_ACTION_GROUP.ATTACHMENT]: [
    AUDIT_ACTION.ATTACHMENT_UPLOAD,
    AUDIT_ACTION.ATTACHMENT_DELETE,
  ],
  [AUDIT_ACTION_GROUP.FOLDER]: [
    AUDIT_ACTION.FOLDER_CREATE,
    AUDIT_ACTION.FOLDER_UPDATE,
    AUDIT_ACTION.FOLDER_DELETE,
  ],
  [AUDIT_ACTION_GROUP.HISTORY]: [
    AUDIT_ACTION.ENTRY_HISTORY_RESTORE,
    AUDIT_ACTION.HISTORY_PURGE,
    AUDIT_ACTION.ENTRY_HISTORY_REENCRYPT,
  ],
  [AUDIT_ACTION_GROUP.TEAM]: [
    AUDIT_ACTION.TEAM_MEMBER_ADD,
    AUDIT_ACTION.TEAM_MEMBER_INVITE,
    AUDIT_ACTION.TEAM_MEMBER_REMOVE,
    AUDIT_ACTION.TEAM_ROLE_UPDATE,
  ],
  [AUDIT_ACTION_GROUP.SHARE]: [
    AUDIT_ACTION.SHARE_CREATE,
    AUDIT_ACTION.SHARE_REVOKE,
    AUDIT_ACTION.SHARE_ACCESS_VERIFY_SUCCESS,
    AUDIT_ACTION.SHARE_ACCESS_VERIFY_FAILED,
  ],
  [AUDIT_ACTION_GROUP.ADMIN]: [
    AUDIT_ACTION.MASTER_KEY_ROTATION,
    AUDIT_ACTION.VAULT_KEY_ROTATION,
    AUDIT_ACTION.TEAM_E2E_MIGRATION,
    AUDIT_ACTION.TEAM_KEY_ROTATION,
    AUDIT_ACTION.TEAM_MEMBER_KEY_DISTRIBUTE,
    AUDIT_ACTION.POLICY_UPDATE,
    AUDIT_ACTION.TEAM_POLICY_CLAMPED_BY_TENANT,
    AUDIT_ACTION.AUDIT_LOG_DOWNLOAD,
    AUDIT_ACTION.WATCHTOWER_ALERT_SENT,
    AUDIT_ACTION.ADMIN_VAULT_RESET_INITIATE,
    // APPROVE included alongside EXECUTE: it is the consequential gate that
    // unlocks execution, so it belongs in the team-admin audit feed.
    AUDIT_ACTION.ADMIN_VAULT_RESET_APPROVE,
    AUDIT_ACTION.ADMIN_VAULT_RESET_EXECUTE,
  ],
  [AUDIT_ACTION_GROUP.SCIM]: [
    AUDIT_ACTION.SCIM_TOKEN_CREATE,
    AUDIT_ACTION.SCIM_TOKEN_REVOKE,
    AUDIT_ACTION.SCIM_USER_CREATE,
    AUDIT_ACTION.SCIM_USER_UPDATE,
    AUDIT_ACTION.SCIM_USER_DEACTIVATE,
    AUDIT_ACTION.SCIM_USER_REACTIVATE,
    AUDIT_ACTION.SCIM_USER_DELETE,
    AUDIT_ACTION.SCIM_GROUP_UPDATE,
  ],
  [AUDIT_ACTION_GROUP.WEBHOOK]: [
    AUDIT_ACTION.WEBHOOK_CREATE,
    AUDIT_ACTION.WEBHOOK_DELETE,
    AUDIT_ACTION.WEBHOOK_DELIVERY_FAILED,
  ],
};

export const AUDIT_ACTION_GROUPS_TENANT: Record<string, AuditAction[]> = {
  [AUDIT_ACTION_GROUP.ADMIN]: [
    AUDIT_ACTION.ADMIN_VAULT_RESET_INITIATE,
    AUDIT_ACTION.ADMIN_VAULT_RESET_APPROVE,
    AUDIT_ACTION.ADMIN_VAULT_RESET_EXECUTE,
    AUDIT_ACTION.ADMIN_VAULT_RESET_REVOKE,
    AUDIT_ACTION.TENANT_ROLE_UPDATE,
    AUDIT_ACTION.POLICY_UPDATE,
    AUDIT_ACTION.TEAM_POLICY_CLAMPED_BY_TENANT,
    AUDIT_ACTION.ACCESS_DENIED,
    AUDIT_ACTION.MASTER_KEY_ROTATION,
    AUDIT_ACTION.VERIFIER_PEPPER_ROTATE_BEGIN,
    AUDIT_ACTION.VERIFIER_PEPPER_ROTATE_COMPLETE,
    AUDIT_ACTION.VERIFIER_PEPPER_ROTATE_ROLLBACK,
    AUDIT_ACTION.VERIFIER_PEPPER_MISSING,
    AUDIT_ACTION.AUDIT_LOG_DOWNLOAD,
    AUDIT_ACTION.HISTORY_PURGE,
    AUDIT_ACTION.AUDIT_LOG_PURGE,
    AUDIT_ACTION.PASSKEY_ENFORCEMENT_BLOCKED,
    AUDIT_ACTION.OPERATOR_TOKEN_CREATE,
    AUDIT_ACTION.OPERATOR_TOKEN_REVOKE,
  ],
  [AUDIT_ACTION_GROUP.SCIM]: [
    AUDIT_ACTION.SCIM_TOKEN_CREATE,
    AUDIT_ACTION.SCIM_TOKEN_REVOKE,
    AUDIT_ACTION.SCIM_USER_CREATE,
    AUDIT_ACTION.SCIM_USER_UPDATE,
    AUDIT_ACTION.SCIM_USER_DEACTIVATE,
    AUDIT_ACTION.SCIM_USER_REACTIVATE,
    AUDIT_ACTION.SCIM_USER_DELETE,
    AUDIT_ACTION.SCIM_GROUP_UPDATE,
  ],
  [AUDIT_ACTION_GROUP.DIRECTORY_SYNC]: [
    AUDIT_ACTION.DIRECTORY_SYNC_CONFIG_CREATE,
    AUDIT_ACTION.DIRECTORY_SYNC_CONFIG_UPDATE,
    AUDIT_ACTION.DIRECTORY_SYNC_CONFIG_DELETE,
    AUDIT_ACTION.DIRECTORY_SYNC_RUN,
    AUDIT_ACTION.DIRECTORY_SYNC_STALE_RESET,
  ],
  [AUDIT_ACTION_GROUP.BREAKGLASS]: [
    AUDIT_ACTION.PERSONAL_LOG_ACCESS_REQUEST,
    AUDIT_ACTION.PERSONAL_LOG_ACCESS_VIEW,
    AUDIT_ACTION.PERSONAL_LOG_ACCESS_REVOKE,
    AUDIT_ACTION.PERSONAL_LOG_ACCESS_EXPIRE,
  ],
  [AUDIT_ACTION_GROUP.TENANT_WEBHOOK]: [
    AUDIT_ACTION.TENANT_WEBHOOK_CREATE,
    AUDIT_ACTION.TENANT_WEBHOOK_DELETE,
    AUDIT_ACTION.TENANT_WEBHOOK_DELIVERY_FAILED,
  ],
  [AUDIT_ACTION_GROUP.SERVICE_ACCOUNT]: [
    AUDIT_ACTION.SERVICE_ACCOUNT_CREATE,
    AUDIT_ACTION.SERVICE_ACCOUNT_UPDATE,
    AUDIT_ACTION.SERVICE_ACCOUNT_DELETE,
    AUDIT_ACTION.SERVICE_ACCOUNT_TOKEN_CREATE,
    AUDIT_ACTION.SERVICE_ACCOUNT_TOKEN_REVOKE,
    AUDIT_ACTION.ACCESS_REQUEST_CREATE,
    AUDIT_ACTION.ACCESS_REQUEST_APPROVE,
    AUDIT_ACTION.ACCESS_REQUEST_DENY,
  ],
  [AUDIT_ACTION_GROUP.MCP_CLIENT]: [
    AUDIT_ACTION.MCP_CLIENT_CREATE,
    AUDIT_ACTION.MCP_CLIENT_UPDATE,
    AUDIT_ACTION.MCP_CLIENT_DELETE,
    AUDIT_ACTION.MCP_CLIENT_DCR_REGISTER,
    AUDIT_ACTION.MCP_CLIENT_DCR_CLAIM,
    AUDIT_ACTION.MCP_CLIENT_DCR_CLEANUP,
    AUDIT_ACTION.MCP_CLIENT_DCR_CLEANUP_DEPRECATED_CALL,
    AUDIT_ACTION.MCP_CONSENT_GRANT,
    AUDIT_ACTION.MCP_CONSENT_DENY,
    AUDIT_ACTION.MCP_REFRESH_TOKEN_ROTATE,
    AUDIT_ACTION.MCP_REFRESH_TOKEN_REPLAY,
  ],
  [AUDIT_ACTION_GROUP.DELEGATION]: [
    AUDIT_ACTION.DELEGATION_CREATE,
    AUDIT_ACTION.DELEGATION_REVOKE,
    AUDIT_ACTION.DELEGATION_EXPIRE,
    AUDIT_ACTION.DELEGATION_READ,
    AUDIT_ACTION.DELEGATION_CHECK,
  ],
  [AUDIT_ACTION_GROUP.MAINTENANCE]: [
    AUDIT_ACTION.AUDIT_OUTBOX_REAPED,
    AUDIT_ACTION.AUDIT_OUTBOX_DEAD_LETTER,
    AUDIT_ACTION.AUDIT_OUTBOX_RETENTION_PURGED,
    AUDIT_ACTION.AUDIT_OUTBOX_METRICS_VIEW,
    AUDIT_ACTION.AUDIT_OUTBOX_PURGE_EXECUTED,
    AUDIT_ACTION.AUDIT_DELIVERY_FAILED,
    AUDIT_ACTION.AUDIT_DELIVERY_DEAD_LETTER,
    AUDIT_ACTION.AUDIT_CHAIN_VERIFY,
  ],
  [AUDIT_ACTION_GROUP.AUDIT_DELIVERY_TARGET]: [
    AUDIT_ACTION.AUDIT_DELIVERY_TARGET_CREATE,
    AUDIT_ACTION.AUDIT_DELIVERY_TARGET_DEACTIVATE,
    AUDIT_ACTION.AUDIT_DELIVERY_TARGET_REACTIVATE,
  ],
};

/**
 * Event groups subscribable via tenant webhooks.
 * Derived from AUDIT_ACTION_GROUPS_TENANT minus self-referential and
 * privacy-sensitive groups. logAuditAsync() dispatches webhooks automatically
 * for all audit actions, so every action here is guaranteed to fire.
 *
 * Intentionally excluded:
 * - TENANT_WEBHOOK group (prevents self-referential loops)
 * - PERSONAL_LOG_ACCESS_VIEW/EXPIRE (privacy-sensitive timing data)
 */
export const TENANT_WEBHOOK_EVENT_GROUPS: Record<string, AuditAction[]> = {
  [AUDIT_ACTION_GROUP.ADMIN]: AUDIT_ACTION_GROUPS_TENANT[AUDIT_ACTION_GROUP.ADMIN],
  [AUDIT_ACTION_GROUP.SCIM]: AUDIT_ACTION_GROUPS_TENANT[AUDIT_ACTION_GROUP.SCIM],
  [AUDIT_ACTION_GROUP.DIRECTORY_SYNC]: AUDIT_ACTION_GROUPS_TENANT[AUDIT_ACTION_GROUP.DIRECTORY_SYNC],
  [AUDIT_ACTION_GROUP.BREAKGLASS]: [
    AUDIT_ACTION.PERSONAL_LOG_ACCESS_REQUEST,
    AUDIT_ACTION.PERSONAL_LOG_ACCESS_REVOKE,
    // VIEW and EXPIRE excluded (privacy-sensitive timing data)
  ],
  [AUDIT_ACTION_GROUP.SERVICE_ACCOUNT]: AUDIT_ACTION_GROUPS_TENANT[AUDIT_ACTION_GROUP.SERVICE_ACCOUNT],
  [AUDIT_ACTION_GROUP.MCP_CLIENT]: AUDIT_ACTION_GROUPS_TENANT[AUDIT_ACTION_GROUP.MCP_CLIENT],
  [AUDIT_ACTION_GROUP.DELEGATION]: AUDIT_ACTION_GROUPS_TENANT[AUDIT_ACTION_GROUP.DELEGATION],
  [AUDIT_ACTION_GROUP.SHARE]: [
    AUDIT_ACTION.SHARE_ACCESS_VERIFY_FAILED,
    AUDIT_ACTION.SHARE_ACCESS_VERIFY_SUCCESS,
    AUDIT_ACTION.SHARE_CREATE,
    AUDIT_ACTION.SHARE_REVOKE,
  ],
};

export const TENANT_WEBHOOK_SUBSCRIBABLE_ACTIONS = Object.values(
  TENANT_WEBHOOK_EVENT_GROUPS,
).flat() as AuditAction[];

/**
 * Event groups subscribable via team webhooks.
 * Derived from AUDIT_ACTION_GROUPS_TEAM with overrides:
 *
 * - WEBHOOK group excluded (prevents self-referential loops)
 * - SCIM group excluded (all tenant-scoped provisioning actions)
 * - ADMIN group replaced with team-scoped subset only:
 *   Includes: TEAM_E2E_MIGRATION, TEAM_KEY_ROTATION,
 *     TEAM_MEMBER_KEY_DISTRIBUTE, POLICY_UPDATE, AUDIT_LOG_DOWNLOAD
 *   Excludes: MASTER_KEY_ROTATION, VAULT_KEY_ROTATION,
 *     WATCHTOWER_ALERT_SENT, ADMIN_VAULT_RESET_* (all tenant/personal-scoped)
 */
const TEAM_WEBHOOK_EXCLUDED_GROUPS: ReadonlySet<string> = new Set([
  AUDIT_ACTION_GROUP.WEBHOOK,
  AUDIT_ACTION_GROUP.SCIM,
  AUDIT_ACTION_GROUP.ADMIN,
]);

export const TEAM_WEBHOOK_EVENT_GROUPS: Record<string, AuditAction[]> = {
  ...Object.fromEntries(
    Object.entries(AUDIT_ACTION_GROUPS_TEAM).filter(
      ([key]) => !TEAM_WEBHOOK_EXCLUDED_GROUPS.has(key),
    ),
  ),
  // Team-scoped subset of the ADMIN group
  [AUDIT_ACTION_GROUP.ADMIN]: [
    AUDIT_ACTION.TEAM_E2E_MIGRATION,
    AUDIT_ACTION.TEAM_KEY_ROTATION,
    AUDIT_ACTION.TEAM_MEMBER_KEY_DISTRIBUTE,
    AUDIT_ACTION.POLICY_UPDATE,
    AUDIT_ACTION.AUDIT_LOG_DOWNLOAD,
  ],
};

export const TEAM_WEBHOOK_SUBSCRIBABLE_ACTIONS = Object.values(
  TEAM_WEBHOOK_EVENT_GROUPS,
).flat() as AuditAction[];

export const AUDIT_METADATA_KEY = {
  HISTORY_ID: "historyId",
  RESTORED_FROM_CHANGED_AT: "restoredFromChangedAt",
  PURGED_COUNT: "purgedCount",
} as const;

export const AUDIT_ACTION_EMERGENCY_PREFIX = "EMERGENCY_";

import { envInt } from "@/lib/env/env-utils";

export const AUDIT_OUTBOX = {
  BATCH_SIZE: envInt("OUTBOX_BATCH_SIZE", 500),
  POLL_INTERVAL_MS: envInt("OUTBOX_POLL_INTERVAL_MS", 1000),
  PROCESSING_TIMEOUT_MS: envInt("OUTBOX_PROCESSING_TIMEOUT_MS", 300_000),
  MAX_ATTEMPTS: envInt("OUTBOX_MAX_ATTEMPTS", 8),
  RETENTION_HOURS: envInt("OUTBOX_RETENTION_HOURS", 24),
  FAILED_RETENTION_DAYS: envInt("OUTBOX_FAILED_RETENTION_DAYS", 90),
  READY_PENDING_THRESHOLD: envInt("OUTBOX_READY_PENDING_THRESHOLD", 10_000),
  READY_OLDEST_THRESHOLD: envInt("OUTBOX_READY_OLDEST_THRESHOLD_SECS", 600),
  REAPER_INTERVAL_MS: envInt("OUTBOX_REAPER_INTERVAL_MS", 30_000),
} as const;

export const OUTBOX_BYPASS_AUDIT_ACTIONS: ReadonlySet<string> = new Set([
  AUDIT_ACTION.WEBHOOK_DELIVERY_FAILED,
  AUDIT_ACTION.TENANT_WEBHOOK_DELIVERY_FAILED,
  AUDIT_ACTION.AUDIT_OUTBOX_REAPED,
  AUDIT_ACTION.AUDIT_OUTBOX_DEAD_LETTER,
  AUDIT_ACTION.AUDIT_OUTBOX_RETENTION_PURGED,
  AUDIT_ACTION.AUDIT_DELIVERY_FAILED,
  AUDIT_ACTION.AUDIT_DELIVERY_DEAD_LETTER,
]);

/**
 * Merge multiple action-group maps by key, producing a Set-based union for
 * duplicate keys so that no actions from either side are silently dropped.
 */
export function mergeActionGroups(
  ...groups: Record<string, AuditAction[]>[]
): Record<string, AuditAction[]> {
  const merged: Record<string, AuditAction[]> = {};
  for (const group of groups) {
    for (const [key, actions] of Object.entries(group)) {
      merged[key] = [...new Set([...(merged[key] ?? []), ...actions])];
    }
  }
  return merged;
}

/**
 * Actions that suppress webhook dispatch entirely.
 * All AUDIT_OUTBOX_* actions are internal operational events
 * that should never trigger external webhook delivery.
 */
export const WEBHOOK_DISPATCH_SUPPRESS: ReadonlySet<string> = new Set([
  AUDIT_ACTION.AUDIT_OUTBOX_REAPED,
  AUDIT_ACTION.AUDIT_OUTBOX_DEAD_LETTER,
  AUDIT_ACTION.AUDIT_OUTBOX_RETENTION_PURGED,
  AUDIT_ACTION.AUDIT_OUTBOX_METRICS_VIEW,
  AUDIT_ACTION.AUDIT_OUTBOX_PURGE_EXECUTED,
  AUDIT_ACTION.AUDIT_DELIVERY_FAILED,
  AUDIT_ACTION.AUDIT_DELIVERY_DEAD_LETTER,
  AUDIT_ACTION.AUDIT_CHAIN_VERIFY,
  AUDIT_ACTION.AUDIT_DELIVERY_TARGET_CREATE,
  AUDIT_ACTION.AUDIT_DELIVERY_TARGET_DEACTIVATE,
  AUDIT_ACTION.AUDIT_DELIVERY_TARGET_REACTIVATE,
]);
