-- Add distinct trash/permanent delete audit actions
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'ENTRY_BULK_TRASH';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'ENTRY_EMPTY_TRASH';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'ENTRY_TRASH';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'ENTRY_PERMANENT_DELETE';
