/**
 * Tests for scripts/generate-security-matrices.ts (C5 of
 * route-policy-sql-security-plan.md).
 *
 * Determinism (in-process, distinct from the pre-pr drift check which only
 * compares against the committed file and cannot catch cross-machine
 * iteration-order nondeterminism): invoke the two render functions twice in
 * the same process and assert byte-identical string output.
 *
 * Content correctness: a determinism test alone would pass even if every
 * row were wrong the same way twice, so this also asserts one known
 * registry-managed model produces a row with the expected columns, and one
 * known non-registry model appears in the "no automated purge" bucket.
 */
import { describe, it, expect } from "vitest";
import {
  renderRoutePolicyMatrix,
  renderDeletionRetentionMatrix,
} from "../generate-security-matrices.ts";
import { RETENTION_REGISTRY } from "../../src/workers/retention-gc-worker/registry.ts";

// Minimal fixture manifest -- exercises the same shape the real
// scripts/checks/route-policy-manifest.json uses, without depending on its
// (large, evolving) content.
const FIXTURE_MANIFEST = {
  routes: {
    "src/app/api/zeta/route.ts": {
      kind: "api-session-required",
      methods: ["GET", "POST"],
      auth: ["session"],
    },
    "src/app/api/alpha/[id]/route.ts": {
      kind: "api-default",
      methods: ["DELETE"],
      auth: ["operator-token"],
      handlerAuthReason: "verifyAdminToken + requireMaintenanceOperator gate",
      destructive: true,
      operatorGated: true,
    },
    "src/app/api/alpha/route.ts": {
      kind: "api-default",
      methods: ["GET"],
      auth: ["none"],
      handlerAuthReason: "Public by design, defended by rate limiting",
      sideEffectingGet: "mints a one-time code",
    },
  },
};

// Minimal fixture dmmf model list: one model in the registry (mcp_clients,
// the first RETENTION_REGISTRY entry) and one known non-registry model.
const FIXTURE_DMMF_MODELS = [
  { name: "McpClient", dbName: "mcp_clients" },
  { name: "Account", dbName: "accounts" },
];

describe("renderRoutePolicyMatrix", () => {
  it("produces byte-identical output across two consecutive in-process calls (determinism)", () => {
    const out1 = renderRoutePolicyMatrix(FIXTURE_MANIFEST);
    const out2 = renderRoutePolicyMatrix(FIXTURE_MANIFEST);
    expect(out1).toBe(out2);
  });

  it("starts with the GENERATED header comment", () => {
    const out = renderRoutePolicyMatrix(FIXTURE_MANIFEST);
    expect(out.startsWith("<!-- GENERATED by scripts/generate-security-matrices.ts")).toBe(true);
  });

  it("sorts routes lexicographically regardless of manifest key insertion order", () => {
    const out = renderRoutePolicyMatrix(FIXTURE_MANIFEST);
    const alphaIdIdx = out.indexOf("src/app/api/alpha/[id]/route.ts");
    const alphaIdx = out.indexOf("src/app/api/alpha/route.ts");
    const zetaIdx = out.indexOf("src/app/api/zeta/route.ts");
    expect(alphaIdIdx).toBeGreaterThan(-1);
    expect(alphaIdx).toBeGreaterThan(-1);
    expect(zetaIdx).toBeGreaterThan(-1);
    // "alpha/[id]" < "alpha/route.ts" lexicographically ('[' < 'r'); both
    // precede "zeta" -- proves the explicit .sort(), not insertion order
    // (FIXTURE_MANIFEST declares zeta first).
    expect(alphaIdIdx).toBeLessThan(alphaIdx);
    expect(alphaIdx).toBeLessThan(zetaIdx);
  });

  it("renders destructive/operatorGated flags and the handlerAuthReason", () => {
    const out = renderRoutePolicyMatrix(FIXTURE_MANIFEST);
    expect(out).toContain("destructive, operatorGated");
    expect(out).toContain(
      "verifyAdminToken + requireMaintenanceOperator gate",
    );
  });

  it("renders the sideEffectingGet reason for a GET-only route", () => {
    const out = renderRoutePolicyMatrix(FIXTURE_MANIFEST);
    expect(out).toContain("sideEffectingGet");
    expect(out).toContain("mints a one-time code");
  });
});

describe("renderDeletionRetentionMatrix", () => {
  it("produces byte-identical output across two consecutive in-process calls (determinism)", () => {
    const out1 = renderDeletionRetentionMatrix(
      RETENTION_REGISTRY,
      FIXTURE_DMMF_MODELS,
    );
    const out2 = renderDeletionRetentionMatrix(
      RETENTION_REGISTRY,
      FIXTURE_DMMF_MODELS,
    );
    expect(out1).toBe(out2);
  });

  it("starts with the GENERATED header comment", () => {
    const out = renderDeletionRetentionMatrix(
      RETENTION_REGISTRY,
      FIXTURE_DMMF_MODELS,
    );
    expect(out.startsWith("<!-- GENERATED by scripts/generate-security-matrices.ts")).toBe(true);
  });

  it("emits a row for a known registry-managed model (mcp_clients) with expected columns", () => {
    const out = renderDeletionRetentionMatrix(
      RETENTION_REGISTRY,
      FIXTURE_DMMF_MODELS,
    );
    // mcp_clients is RETENTION_REGISTRY[0]: kind EXPIRY, cutoffColumn dcr_expires_at.
    const lines = out.split("\n");
    const row = lines.find((l) => l.includes("`mcp_clients`"));
    expect(row).toBeDefined();
    expect(row).toContain("EXPIRY");
    expect(row).toContain("dcr_expires_at");
  });

  it("lists a known non-registry model (Account/accounts) under the no-automated-purge section", () => {
    const out = renderDeletionRetentionMatrix(
      RETENTION_REGISTRY,
      FIXTURE_DMMF_MODELS,
    );
    const purgeSectionStart = out.indexOf(
      "## No automated purge (manual or cascade-only deletion)",
    );
    expect(purgeSectionStart).toBeGreaterThan(-1);
    const purgeSection = out.slice(purgeSectionStart);
    expect(purgeSection).toContain("`Account`");
    expect(purgeSection).toContain("`accounts`");

    // Must NOT also appear in the registry-managed section above it.
    const registrySection = out.slice(0, purgeSectionStart);
    expect(registrySection).not.toContain("`accounts`");
  });

  it("every registry table is excluded from the no-automated-purge section", () => {
    // Guards against a future bug where the managedTables filter breaks and a
    // registry-managed table leaks into both sections.
    const models = [
      { name: "McpClient", dbName: "mcp_clients" },
      { name: "Account", dbName: "accounts" },
    ];
    const out = renderDeletionRetentionMatrix(RETENTION_REGISTRY, models);
    const purgeSectionStart = out.indexOf(
      "## No automated purge (manual or cascade-only deletion)",
    );
    const purgeSection = out.slice(purgeSectionStart);
    for (const entry of RETENTION_REGISTRY) {
      expect(purgeSection).not.toContain(`\`${entry.table}\``);
    }
  });

  it("every real Prisma model has a non-null dbName (keeps the renderer's `?? name` fallback dead)", async () => {
    // The renderer keys models by `model.dbName ?? model.name`. RETENTION_REGISTRY
    // keys by lowercase table name, so if a model lacked @@map (dbName null) the
    // fallback would emit the PascalCase model name and a registry-managed model
    // could silently leak into the no-automated-purge bucket. Assert the fallback
    // never activates on the real schema, closing that gap mechanically rather
    // than trusting the @@map convention.
    const { Prisma } = await import("@prisma/client");
    const nullDbName = Prisma.dmmf.datamodel.models
      .filter((m) => m.dbName == null)
      .map((m) => m.name);
    expect(nullDbName).toEqual([]);
  });
});
