import {
  LogIn,
  LogOut,
  Plus,
  Archive,
  Pencil,
  Trash2,
  RotateCcw,
  Download,
  Upload,
  UserPlus,
  UserMinus,
  ShieldCheck,
  ShieldAlert,
  ShieldOff,
  ScrollText,
  Link as LinkIcon,
  Link2Off,
  HeartPulse,
  KeyRound,
  Eye,
} from "lucide-react";
import {
  AUDIT_ACTION,
  type AuditActionValue,
} from "@/lib/constants";

// Shared action icon map used by all audit log views (personal, team, tenant).
// Actions without a mapping fall back to <ScrollText /> at the call site.
export const ACTION_ICONS: Partial<Record<AuditActionValue, React.ReactNode>> = {
  [AUDIT_ACTION.AUTH_LOGIN]: <LogIn className="h-4 w-4" />,
  [AUDIT_ACTION.AUTH_LOGOUT]: <LogOut className="h-4 w-4" />,
  [AUDIT_ACTION.ENTRY_BULK_TRASH]: <Trash2 className="h-4 w-4" />,
  [AUDIT_ACTION.ENTRY_EMPTY_TRASH]: <Trash2 className="h-4 w-4" />,
  [AUDIT_ACTION.ENTRY_BULK_ARCHIVE]: <Archive className="h-4 w-4" />,
  [AUDIT_ACTION.ENTRY_BULK_UNARCHIVE]: <RotateCcw className="h-4 w-4" />,
  [AUDIT_ACTION.ENTRY_BULK_RESTORE]: <RotateCcw className="h-4 w-4" />,
  [AUDIT_ACTION.ENTRY_IMPORT]: <Upload className="h-4 w-4" />,
  [AUDIT_ACTION.ENTRY_BULK_IMPORT]: <Upload className="h-4 w-4" />,
  [AUDIT_ACTION.ENTRY_CREATE]: <Plus className="h-4 w-4" />,
  [AUDIT_ACTION.ENTRY_UPDATE]: <Pencil className="h-4 w-4" />,
  [AUDIT_ACTION.ENTRY_DELETE]: <Trash2 className="h-4 w-4" />,
  [AUDIT_ACTION.ENTRY_TRASH]: <Trash2 className="h-4 w-4" />,
  [AUDIT_ACTION.ENTRY_PERMANENT_DELETE]: <Trash2 className="h-4 w-4" />,
  [AUDIT_ACTION.ENTRY_RESTORE]: <RotateCcw className="h-4 w-4" />,
  [AUDIT_ACTION.ENTRY_EXPORT]: <Download className="h-4 w-4" />,
  [AUDIT_ACTION.ATTACHMENT_UPLOAD]: <Upload className="h-4 w-4" />,
  [AUDIT_ACTION.ATTACHMENT_DELETE]: <Trash2 className="h-4 w-4" />,
  [AUDIT_ACTION.TEAM_MEMBER_INVITE]: <UserPlus className="h-4 w-4" />,
  [AUDIT_ACTION.TEAM_MEMBER_REMOVE]: <UserMinus className="h-4 w-4" />,
  [AUDIT_ACTION.TEAM_ROLE_UPDATE]: <ShieldCheck className="h-4 w-4" />,
  [AUDIT_ACTION.SHARE_CREATE]: <LinkIcon className="h-4 w-4" />,
  [AUDIT_ACTION.SHARE_REVOKE]: <Link2Off className="h-4 w-4" />,
  [AUDIT_ACTION.EMERGENCY_GRANT_CREATE]: <HeartPulse className="h-4 w-4" />,
  [AUDIT_ACTION.EMERGENCY_GRANT_ACCEPT]: <HeartPulse className="h-4 w-4" />,
  [AUDIT_ACTION.EMERGENCY_GRANT_REJECT]: <ShieldOff className="h-4 w-4" />,
  [AUDIT_ACTION.EMERGENCY_GRANT_CONFIRM]: <KeyRound className="h-4 w-4" />,
  [AUDIT_ACTION.EMERGENCY_ACCESS_REQUEST]: <ShieldAlert className="h-4 w-4" />,
  [AUDIT_ACTION.EMERGENCY_ACCESS_ACTIVATE]: <ShieldCheck className="h-4 w-4" />,
  [AUDIT_ACTION.EMERGENCY_ACCESS_REVOKE]: <ShieldOff className="h-4 w-4" />,
  [AUDIT_ACTION.EMERGENCY_VAULT_ACCESS]: <Eye className="h-4 w-4" />,
};

export const DEFAULT_AUDIT_ICON = <ScrollText className="h-4 w-4" />;
