/**
 * Generates the Route Policy Matrix and Deletion/Retention Matrix docs
 * (C5 of route-policy-sql-security-plan.md) from their machine-readable
 * sources:
 *   - Route Policy Matrix   <- scripts/checks/route-policy-manifest.json (C1)
 *   - Deletion/Retention Matrix <- src/workers/retention-gc-worker/registry.ts
 *     (RETENTION_REGISTRY) + Prisma.dmmf.datamodel.models (authoritative model list)
 *
 * Determinism (NF3 / forbidden-pattern: no `new Date()` in the output path):
 * both docs must be byte-identical across repeated runs on the same inputs so
 * the pre-pr drift check (`generate -> git diff --quiet`) is meaningful. Two
 * distinct sort strategies are used, one per data source, each justified
 * where applied (mirrors the sort-strategy comment in
 * scripts/generate-env-example.ts):
 *   - route-policy-manifest.json keys: explicit `.sort()` (lexicographic on
 *     the repo-relative path string) -- JSON.parse does not guarantee key
 *     enumeration order is preserved identically across engines/versions for
 *     arbitrary string keys, so we never rely on iteration order.
 *   - Prisma.dmmf.datamodel.models: NOT re-sorted -- this array's order is
 *     schema-declaration order, which is stable because it is generated
 *     directly from the (checked-in, reviewed) schema.prisma text. Re-sorting
 *     would hide accidental model reordering in the schema.
 *
 * Run: tsx scripts/generate-security-matrices.ts
 */

import * as fs from "node:fs";
import * as path from "node:path";
import { fileURLToPath } from "node:url";
import { Prisma } from "@prisma/client";
import {
  RETENTION_REGISTRY,
  type RetentionEntry,
} from "@/workers/retention-gc-worker/registry";

const GENERATED_HEADER =
  "<!-- GENERATED by scripts/generate-security-matrices.ts -- do not edit by hand -->";

const SCRIPT_DIR = path.dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = path.resolve(SCRIPT_DIR, "..");
const MANIFEST_PATH = path.join(
  REPO_ROOT,
  "scripts",
  "checks",
  "route-policy-manifest.json",
);
const ROUTE_POLICY_OUT = path.join(
  REPO_ROOT,
  "docs",
  "security",
  "route-policy-matrix.md",
);
const DELETION_RETENTION_OUT = path.join(
  REPO_ROOT,
  "docs",
  "security",
  "deletion-retention-matrix.md",
);

// ── Shared types ────────────────────────────────────────────────────────────

type ManifestRouteEntry = {
  kind: string;
  methods: readonly string[];
  auth?: readonly string[];
  bearerBypass?: readonly string[];
  handlerAuthReason?: string;
  destructive?: boolean;
  sideEffectingGet?: string;
  operatorGated?: boolean;
};

type Manifest = {
  routes: Record<string, ManifestRouteEntry>;
};

// ── Markdown helpers ────────────────────────────────────────────────────────

/** Escape a value for safe placement inside a `|`-delimited Markdown table cell. */
function cell(value: string | undefined): string {
  if (value === undefined || value === "") return "-";
  return value.replace(/\|/g, "\\|").replace(/\n/g, " ");
}

function flagsCell(entry: ManifestRouteEntry): string {
  const flags: string[] = [];
  if (entry.destructive) flags.push("destructive");
  if (entry.sideEffectingGet) flags.push("sideEffectingGet");
  if (entry.operatorGated === true) flags.push("operatorGated");
  if (entry.operatorGated === false) flags.push("operatorGated=false");
  return flags.length > 0 ? flags.join(", ") : "-";
}

function reasonCell(entry: ManifestRouteEntry): string {
  const reasons = [entry.handlerAuthReason, entry.sideEffectingGet].filter(
    (r): r is string => Boolean(r),
  );
  return reasons.length > 0 ? reasons.join(" / ") : "-";
}

/**
 * The top-level area segment of a route path, e.g.
 * "src/app/api/passwords/[id]/route.ts" -> "passwords". Used purely for
 * readability grouping in the generated doc; has no bearing on security
 * classification.
 */
function routeArea(routePath: string): string {
  const parts = routePath.split("/");
  return parts[3] ?? "(root)";
}

// ── Route Policy Matrix ─────────────────────────────────────────────────────

export function renderRoutePolicyMatrix(manifest: Manifest): string {
  const lines: string[] = [];
  lines.push(GENERATED_HEADER);
  lines.push("");
  lines.push("# Route Policy Matrix");
  lines.push("");
  lines.push(
    "One row per `src/app/api/**/route.ts` file, sourced from " +
      "`scripts/checks/route-policy-manifest.json` (C1). Verified fields " +
      "(`kind`, `methods`, `bearerBypass`, `destructive`, `sideEffectingGet` " +
      "floor, `operatorGated`) are asserted by " +
      "`src/__tests__/proxy/route-policy-manifest.test.ts`; `auth` and " +
      "`handlerAuthReason` are doc fields, review-enforced.",
  );
  lines.push("");
  lines.push(
    "Routes are grouped by their top-level API area for readability " +
      "(grouping is cosmetic, not a security classification).",
  );
  lines.push("");

  // Explicit .sort() on manifest keys -- see file header comment for why.
  const sortedPaths = Object.keys(manifest.routes).sort();

  const byArea = new Map<string, string[]>();
  for (const routePath of sortedPaths) {
    const area = routeArea(routePath);
    const list = byArea.get(area) ?? [];
    list.push(routePath);
    byArea.set(area, list);
  }

  // Areas themselves are derived from sortedPaths insertion order above, which
  // is already lexicographic on the full path -- so area names come out sorted.
  const sortedAreas = [...byArea.keys()].sort();

  for (const area of sortedAreas) {
    lines.push(`## ${area}`);
    lines.push("");
    lines.push(
      "| Path | Kind | Methods | Auth | Bearer bypass | Flags | Reason |",
    );
    lines.push(
      "| --- | --- | --- | --- | --- | --- | --- |",
    );
    for (const routePath of byArea.get(area) ?? []) {
      const entry = manifest.routes[routePath];
      lines.push(
        `| \`${routePath}\` | ${cell(entry.kind)} | ${cell(entry.methods.join(", "))} | ${cell(entry.auth?.join(", "))} | ${cell(entry.bearerBypass?.join(", "))} | ${flagsCell(entry)} | ${reasonCell(entry)} |`,
      );
    }
    lines.push("");
  }

  return lines.join("\n").trimEnd() + "\n";
}

// ── Deletion / Retention Matrix ──────────────────────────────────────────────

function retentionEntryCutoffSource(entry: RetentionEntry): string {
  switch (entry.kind) {
    case "PER_TENANT_FN":
      return "n/a (SECURITY DEFINER fn)";
    case "PER_TENANT_TRASH":
      return "n/a (soft-delete `deleted_at` sweep)";
    case "EXPIRY":
    case "EXPIRY_GUARDED":
    case "EXPIRY_AUDIT_PROVENANCE":
    case "PER_TENANT_AGE":
      return `\`${entry.cutoffColumn}\``;
  }
}

function retentionEntryTenantPolicyColumn(entry: RetentionEntry): string {
  if (entry.kind === "EXPIRY" || entry.kind === "EXPIRY_GUARDED") {
    return "-";
  }
  if (entry.kind === "EXPIRY_AUDIT_PROVENANCE") {
    return "-";
  }
  return `\`tenants.${entry.tenantRetentionColumn}\``;
}

function retentionEntryFloor(entry: RetentionEntry): string {
  if (entry.kind === "PER_TENANT_FN") {
    return "clamped to AUDIT_LOG_RETENTION_MIN floor (sweep.ts)";
  }
  if (entry.kind === "EXPIRY_GUARDED") {
    return `guard: \`${entry.guard}\` (no live dependents)`;
  }
  if (entry.kind === "EXPIRY_AUDIT_PROVENANCE" && entry.guard) {
    return `guard: \`${entry.guard}\` (no live dependents)`;
  }
  return "-";
}

function retentionEntryAuditAction(entry: RetentionEntry): string {
  if (entry.kind === "EXPIRY_AUDIT_PROVENANCE") return entry.auditAction;
  if (entry.kind === "PER_TENANT_AGE") return entry.auditAction;
  return "-";
}

function retentionEntryTable(entry: RetentionEntry): string {
  return entry.table;
}

export function renderDeletionRetentionMatrix(
  registry: readonly RetentionEntry[],
  dmmfModels: readonly { name: string; dbName: string | null }[],
): string {
  const lines: string[] = [];
  lines.push(GENERATED_HEADER);
  lines.push("");
  lines.push("# Deletion / Retention Matrix");
  lines.push("");
  lines.push(
    "Sourced from `src/workers/retention-gc-worker/registry.ts` " +
      "(`RETENTION_REGISTRY`) for managed tables, and " +
      "`Prisma.dmmf.datamodel.models` for the authoritative full model list " +
      "(no fragile schema.prisma regex parsing). Every Prisma model appears " +
      "in exactly one of the two sections below.",
  );
  lines.push("");
  lines.push("## Registry-managed models");
  lines.push("");
  lines.push(
    "| Table | Kind | Cutoff source | Tenant policy column | Floor / guard | Audit action |",
  );
  lines.push("| --- | --- | --- | --- | --- | --- |");

  // Registry order is source order (RETENTION_REGISTRY is a fixed literal
  // array in registry.ts) -- deterministic by construction, no re-sort needed.
  for (const entry of registry) {
    lines.push(
      `| \`${retentionEntryTable(entry)}\` | ${entry.kind} | ${retentionEntryCutoffSource(entry)} | ${retentionEntryTenantPolicyColumn(entry)} | ${retentionEntryFloor(entry)} | ${retentionEntryAuditAction(entry)} |`,
    );
  }
  lines.push("");

  const managedTables = new Set(registry.map((e) => e.table));

  lines.push("## No automated purge (manual or cascade-only deletion)");
  lines.push("");
  lines.push(
    "Every remaining Prisma model, i.e. models with no row in the registry " +
      "above. These are deleted only via explicit application code (manual " +
      "user/admin action) or as an `ON DELETE CASCADE` side effect of a " +
      "parent-row deletion -- never by the retention-GC worker's own sweep.",
  );
  lines.push("");
  lines.push("| Model | Table |");
  lines.push("| --- | --- |");

  // dmmfModels is NOT re-sorted -- see file header comment: order is
  // schema-declaration order, stable because schema.prisma is checked-in text.
  for (const model of dmmfModels) {
    const table = model.dbName ?? model.name;
    if (managedTables.has(table)) continue;
    lines.push(`| \`${model.name}\` | \`${table}\` |`);
  }
  lines.push("");

  return lines.join("\n").trimEnd() + "\n";
}

// ── CLI entry point ──────────────────────────────────────────────────────────

function readManifest(): Manifest {
  const raw = fs.readFileSync(MANIFEST_PATH, "utf8");
  return JSON.parse(raw) as Manifest;
}

function main(): void {
  const manifest = readManifest();
  const routePolicyMd = renderRoutePolicyMatrix(manifest);
  fs.writeFileSync(ROUTE_POLICY_OUT, routePolicyMd, "utf8");
  console.log(`Wrote ${ROUTE_POLICY_OUT}`);

  const dmmfModels = Prisma.dmmf.datamodel.models.map((m) => ({
    name: m.name,
    dbName: m.dbName ?? null,
  }));
  const deletionRetentionMd = renderDeletionRetentionMatrix(
    RETENTION_REGISTRY,
    dmmfModels,
  );
  fs.writeFileSync(DELETION_RETENTION_OUT, deletionRetentionMd, "utf8");
  console.log(`Wrote ${DELETION_RETENTION_OUT}`);
}

if (import.meta.url === `file://${process.argv[1]}`) {
  main();
}
